const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('src/demo.js','utf8').split('\nwindow.KnowHowCompanyLive=')[0].replace('return {activate,deactivate,isActive:()=>active,openVisitorContext};','return {activate,deactivate,isActive:()=>active,openVisitorContext,state,openSelected,createLiveDraft,postComment,reviseDocument,reviewDocument,ask,connectionEvidence,request,render};');
const clone=x=>JSON.parse(JSON.stringify(x)),credential='test-memory-only-credential';
const selection={context_id:'a'.repeat(32),dataset_id:'b'.repeat(32),department:'device',station:{name:'Fresh selected station',address:'New address',operator:'Public operator'},records:[{row_number:18,public_charger_id:'01',fields:{}},{row_number:19,public_charger_id:'02',fields:{}}],source:{source_sha256:'c'.repeat(64),source_bytes:12345,source_url:'https://example.org/original.csv',fetched_at:'2026-09-21T00:00:00Z'},fingerprint:'d'.repeat(64)};
function setup(hash='#data'){
 const storage=new Map([['knowhow.scenarios.v1','OLD LEGACY SENTINEL']]);let reads=0;const nodes=new Map(['#page','#session','#connection','.workspace','.aside-note','nav'].map(k=>[k,{innerHTML:k==='#page'?'PREVIOUS PAGE':'',textContent:'',hidden:false}]));
 const c=vm.createContext({console,URL,AbortSignal,TextEncoder,location:{hash},history:{replaceState(a,b,h){c.location.hash=h}},window:{KNOWHOW_CONFIG:{apiBase:'https://old.example/knowhow',aiRequestsPaused:false},scrollTo(){},addEventListener(){}},document:{querySelector:s=>nodes.get(s)||null,querySelectorAll:()=>[]},localStorage:{getItem:k=>{reads++;return storage.get(k)||null},setItem:(k,v)=>storage.set(k,v)}});
 vm.runInContext("let sessionGeneration=0,token='PRIVATE',user={id:'secret'},docs=[],selected=null;const clearWorkflow=()=>{};const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));",c);vm.runInContext(fs.readFileSync('src/demo-example.js','utf8'),c);vm.runInContext(source,c);return {c,api:vm.runInContext('sampleDemo',c),storage,nodes,reads:()=>reads};
}
const response=(value,status=200)=>({ok:status<400,status,json:async()=>clone(value)});
(async()=>{
 const x=setup(),{c,api,storage,nodes}=x;const initialStorage=clone([...storage]);let calls=[],doc=null,denied=false,capabilities={},expectedGenerate=false;
 c.fetch=async(url,options)=>{const body=JSON.parse(options.body||'{}');calls.push({url,method:options.method,body,authorized:options.headers.Authorization==='Bearer '+credential});assert.ok(!url.includes(credential));assert.ok(!url.includes(selection.context_id));assert.equal(options.credentials,'omit');assert.equal(options.headers.Authorization,'Bearer '+credential);for(const key of ['org','session_id','sample_pack','source'])assert.equal(body[key],undefined,'visitor request cannot import demo identity or client provenance');if(denied)return response({error:'Forbidden'},403);if(url.endsWith('/station-contexts/resolve'))return response({...selection,capabilities});const action=url.split('/').at(-1);assert.equal(body.department,'device');if(action==='catalog')return response({documents:doc?[doc]:[],capabilities});if(action==='data-draft'){assert.equal(body.context_id,selection.context_id);assert.equal(body.dataset_id,selection.dataset_id);doc={id:'e'.repeat(32),title:'Server-generated fresh guide',department:'device',version:1,state:'draft',content:'Fresh source row 18 and 19\nInternal ID requires confirmation.',source:{kind:'data-platform-guide',context_id:selection.context_id,dataset_id:selection.dataset_id,manifest_id:'f'.repeat(32)},comments:[],history:[]};doc.history=[{version:1,state:'draft',content:doc.content}];return response(doc)}if(action==='document')return response({...doc,capabilities});if(action==='comment'){doc.comments.push({id:'comment1',version:doc.version,body:body.body,author_role:'member',resolved_version:null});return response({comment:doc.comments[0],comments:doc.comments})}if(action==='review'){doc.state='confirmed';doc.history.at(-1).state='confirmed';if(doc.version===2)doc.comments[0].resolved_version=2;return response(doc)}if(action==='revise'){assert.equal(body.identifiers,undefined);doc.version++;doc.state='draft';doc.content=body.content;doc.history.push({version:doc.version,state:'draft',content:doc.content});return response(doc)}if(action==='compare-versions')return response({before:doc.history[0],after:doc.history.at(-1)});if(action==='chat'){assert.equal(body.document_id,doc.id);assert.equal(body.generate,expectedGenerate);assert.equal(body.include_company,false);return response({ai_generated:body.generate,answer:body.generate?'Mock only':null,evidence:[{id:doc.id,version:doc.version,text:doc.content}]})}throw Error('Unexpected visitor action '+action)};
 const args={apiBase:'http://127.0.0.1:18771/data-platform',visitorBearer:credential,contextId:selection.context_id};
 denied=true;await assert.rejects(()=>api.openVisitorContext(args),/접근할 수 없거나/);assert.equal(nodes.get('#page').innerHTML,'PREVIOUS PAGE');assert.equal(c.location.hash,'#data');assert.deepEqual(clone([...storage]),initialStorage);denied=false;
 await api.openVisitorContext(args);assert.equal(c.location.hash,'#scenario-1-live');assert.equal(calls.filter(x=>x.url.includes('/kb/')).length,0,'context handoff does not create a document or confirm anything');assert.equal(api.state.station.name,'Fresh selected station');assert.equal(api.state.department,'device');assert.ok(!nodes.get('#page').innerHTML.includes('DEMO-DEVICE'));assert.ok(api.connectionEvidence().includes('ID 확인 필요'));assert.ok(!JSON.stringify(api.state).includes(credential));assert.deepEqual(clone([...storage]),initialStorage);
 await api.openSelected();assert.equal(api.state.document,null);await api.createLiveDraft();const id=api.state.document.id;assert.equal(api.state.document.state,'draft');assert.equal(calls.filter(x=>x.url.endsWith('/review')).length,0);await api.postComment('Add the incident timestamp');api.state.role='reviewer';await api.reviewDocument();await api.reviseDocument({content:'Corrected fresh guide\nAdd incident timestamp.',reason:'Clarify inquiry',department_identifier:'MUST NOT BE SENT',resolve_comment_ids:['comment1']});assert.equal(api.state.document.id,id);assert.equal(api.state.document.version,2);assert.equal(api.state.document.source.context_id,selection.context_id);await api.reviewDocument();await assert.rejects(()=>api.ask({question:'What should I send?',as_of:'2026-09-21',answer_mode:'inquiry',generate:true}),/지원하지 않습니다/);await api.ask({question:'What should I send?',as_of:'2026-09-21',answer_mode:'knowledge',generate:false});assert.equal(api.state.answer.evidence[0].version,2);assert.ok(calls.every(x=>!x.url.includes('/demo/')));assert.deepEqual(clone([...storage]),initialStorage);api.state.tab=4;api.render();assert.ok(!nodes.get('#page').innerHTML.includes('data-generate="true"'));assert.ok(nodes.get('#page').innerHTML.includes('원문 근거만 조회'));
 capabilities={knowledge_generation:true,inquiry_generation:true};await api.openSelected();api.state.tab=4;api.render();assert.ok(nodes.get('#page').innerHTML.includes('data-generate="true"'));assert.equal(calls.filter(x=>x.body.generate===true).length,0,'capability visibility never triggers generation');expectedGenerate=true;await api.ask({question:'Explain this current document',as_of:'2026-09-21',answer_mode:'inquiry',generate:true});assert.equal(calls.filter(x=>x.body.generate===true).length,1);assert.equal(calls.at(-1).body.document_id,id);capabilities={};await assert.rejects(()=>api.ask({question:'Do not generate if support was revoked',as_of:'2026-09-21',answer_mode:'knowledge',generate:true}),/지원하지 않습니다/);assert.equal(calls.filter(x=>x.body.generate===true).length,1);
 // Source revalidation or ACL failure must not fall back to demo data.
 denied=true;await assert.rejects(()=>api.request('kb','document',{id}),/접근할 수 없거나/);api.render();assert.ok(nodes.get('#page').innerHTML.includes('입수한 자료에서 다시 선택'));assert.ok(!nodes.get('#page').innerHTML.includes('Fresh selected station'));denied=false;
 c.location.hash='#data';api.deactivate();assert.equal(api.isActive(),false);assert.ok(!api.state.document,'leaving visitor mode restores its separate prior demo state');assert.deepEqual(clone([...storage]),initialStorage);
 const fresh=setup('#scenario-4-live');fresh.c.fetch=()=>{throw Error('reload must not restore credentials or call API')};assert.equal(fresh.reads(),0,'visitor reload does not read demo session storage');fresh.api.activate();assert.ok(fresh.nodes.get('#page').innerHTML.includes('입수한 자료에서 다시 선택'));assert.ok(!fresh.nodes.get('#page').innerHTML.includes('GS타워'));assert.ok(!fresh.nodes.get('#page').innerHTML.includes('OLD LEGACY'));assert.equal(fresh.reads(),0);
 const race=setup();let release;race.c.fetch=()=>new Promise(resolve=>{release=resolve});const pending=race.api.openVisitorContext(args);race.api.deactivate();release(response(selection));await assert.rejects(()=>pending,e=>e.constructor.name==='Obsolete');assert.equal(race.nodes.get('#page').innerHTML,'PREVIOUS PAGE');
 console.log('PASS: server-resolved context, denied handoff preserves page, memory-only bearer, token/context absent from URL/storage, no demo mixing, explicit server draft and review, immutable provenance on revise, latest source-only query, capability-gated explicit generation and revocation, stale handoff rejection, reload recovery without any credential restore');
})().catch(e=>{console.error(e.message);process.exitCode=1});
