'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sessionGeneration=0;
class StaleSessionError extends Error {}
let base=window.KNOWHOW_CONFIG?.apiBase||'', token='',user=null,page='ask',docs=[],selected=null,xlsxFile=null;
const example='가상 예시 — 실제 내부 자료나 정책이 아닙니다.\n고객 안내에는 CNUM을 사용합니다. 개발·통신 식별자는 modem_id입니다.\n대외 BID/SID/CID는 외부 시스템 식별자이며 내부 CNUM과 동일하다고 가정하지 않습니다.\n충전기 대조: 가상 CNUM EX-001 / modem_id MODEM-DEMO-01. 대외 ID와의 연결 관계 및 적용 기간은 미확인입니다.';
function badge(s){return `<span class="badge ${/상충|거절/.test(s)?'bad':/확인된|^확인$|^정정$/.test(s)?'good':'warn'}">${esc(s)}</span>`}
function notify(s){$('#message').textContent=s}
function connection(){ $('#connection').textContent=user?`${user.org} · ${user.name} · ${user.role==='admin'?'담당자':'구성원'} | API 연결: ${base}`:'API 미연결 · 서버 주소와 계정으로 로그인하면 기록을 조회하고 저장할 수 있습니다.';$('#session').textContent=user?'로그아웃':'API 연결'; }
function requireLogin(){if(!user){openLogin();return false}return true}
function openLogin(){$('#login-form').elements.base.value=base;$('#login-error').textContent='';$('#login').showModal()}
function validBase(value){const u=new URL(value);if(u.username||u.password||u.search||u.hash||u.pathname!=='/'||!(u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname))))throw Error('경로 없는 HTTPS API 주소를 입력하세요. 로컬 호스트만 HTTP를 허용합니다.');return u.origin}
async function api(path,data){const generation=sessionGeneration;const response=await fetch(base+path,{method:data===undefined?'GET':'POST',credentials:'omit',headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(60000)});if(generation!==sessionGeneration)throw new StaleSessionError();let body;try{body=await response.json()}catch{throw Error('API가 JSON 응답을 반환하지 않았습니다. 주소를 확인하세요.')}if(generation!==sessionGeneration)throw new StaleSessionError();if(!response.ok){if(response.status===401){sessionGeneration++;token='';user=null;docs=[];selected=null;connection();render()}throw Error(`${response.status} · ${body.error||'요청 실패'}${response.status===409?' 입력을 보관한 뒤 원문을 다시 조회하세요.':''}`)}return body}
async function run(button,task){if(button)button.disabled=true;notify('');try{await task()}catch(e){if(e instanceof StaleSessionError)return;notify(e.name==='TypeError'?'API 연결 실패 · 서버 주소, 실행 상태와 CORS 설정을 확인한 뒤 다시 시도하세요.':e.message)}finally{if(button)button.disabled=false}}
function heading(k,t,d){return `<div class="hero"><div class="eyebrow">${k}</div><h1>${t}</h1><p>${d}</p></div>`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='ask')renderAsk();if(page==='docs')renderDocs();if(page==='upload')renderUpload()}
function renderAsk(){$('#page').innerHTML=heading('ASK WITH CONTEXT','어떤 업무를 해결하고 있나요?','질문에 업무 맥락과 적용일을 더해, 지금 쓸 수 있는 근거를 찾으세요.')+`<form id="ask-form" class="card"><label>업무 질문<textarea name="question" placeholder="고객에게 어떤 충전기 번호를 안내하나요?" required maxlength="1000"></textarea></label><div class="grid"><label>업무 맥락<input name="context" placeholder="예: 고객 안내" required></label><label>적용일<input name="as_of" type="date" value="${new Date().toLocaleDateString('en-CA')}" required></label></div><label class="check"><input type="checkbox" name="generate"> AI 설명 요청 · 모델 연결 시에도 미확인 초안</label><div class="actions"><button class="primary">근거 찾기 →</button></div><p class="muted">담당자 등록 답변은 질문·맥락·기간이 일치할 때 재사용됩니다.</p></form><div id="result" aria-live="polite"></div><div class="row"><h3>하나의 번호, 서로 다른 업무</h3><span class="badge">가상 예시 · 실제 내부 자료 아님</span></div><div class="triple"><div class="sample">01 · 고객 안내<strong>CNUM</strong><p>고객이 확인하는 번호의 의미와 사용 맥락</p></div><div class="sample">02 · 개발 / 통신<strong>modem_id</strong><p>개발·통신 식별자와 장비 대조</p></div><div class="sample">03 · 대외 연계<strong>BID / SID / CID</strong><p>외부 식별자의 의미와 연결 관계 확인</p></div></div>`;
$('#ask-form').onsubmit=e=>{e.preventDefault();if(!requireLogin())return;const f=e.target;run(f.querySelector('button'),async()=>{const r=await api('/api/ask',{question:f.question.value.trim(),context:f.context.value.trim(),as_of:f.as_of.value,generate:f.generate.checked});$('#result').innerHTML=`<div class="card">${badge(r.status)}<p class="muted">${esc(r.mode)}</p><div class="answer">${esc(r.answer||r.notice||'생성된 답변이 없습니다. 원문 근거를 확인하세요.')}</div><p class="muted">${r.answerable?'담당자가 등록한 답변입니다. 아래 출처와 적용 기간을 함께 확인하세요.':'확정 답변으로 사용하지 마세요. 원문을 열어 담당자에게 확인을 요청할 수 있습니다.'}</p>${(r.evidence||[]).map(x=>`<div class="evidence"><div class="row"><strong>${esc(x.name)}</strong>${badge(x.state)}</div><p>${esc(x.text)}</p><p class="muted">v${x.version} · ${esc(x.location)} ${x.source?' · '+esc(x.source.sheet)+'!'+esc(x.source.cell):''} ${x.reviewer?'· 확인 '+esc(x.reviewer):''}${x.valid_from?' · '+esc(x.valid_from)+' ~ '+esc(x.valid_to):''}</p><button data-open="${x.id}" data-version="${x.version}">원문과 확인 요청 →</button></div>`).join('')||'<p class="empty">표시할 근거가 없습니다. 기록을 입수하거나 질문을 바꿔보세요.</p>'}</div>`;bindOpen()})}}
function bindOpen(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>run(b,()=>openDoc(Number(b.dataset.open),Number(b.dataset.version)||undefined)))}
async function loadDocs(){if(!requireLogin())return;docs=(await api('/api/docs')).docs;renderDocs()}
function renderDocs(){$('#page').innerHTML=heading('KNOWLEDGE LIBRARY','지식 기록','원문부터 확인 이력까지, 팀이 함께 쌓아가는 업무 지식입니다.')+`<div class="row"><span class="muted">${user?docs.length+'개의 접근 가능한 기록':'로그인 후 기록을 조회하세요.'}</span><button id="refresh">새로고침</button></div>${docs.map(d=>`<button class="doc" data-open="${d.id}"><span><strong>${esc(d.name)}</strong><small>${esc(d.owner)} · ${d.scope==='private'?'나만 보기':'조직 공유'} · v${d.current}</small></span>${badge(d.state)}</button>`).join('')||'<div class="card empty">아직 표시할 기록이 없습니다. MD·TXT·CSV 원문을 직접 등록하세요.</div>'}`;$('#refresh').onclick=e=>run(e.target,loadDocs);bindOpen()}
function renderUpload(){xlsxFile=null;$('#page').innerHTML=heading('CAPTURE KNOWLEDGE','흩어진 기록을 한곳으로','원문을 등록하고, 확인이 필요한 내용을 팀과 함께 정리하세요.')+`<form id="upload-form" class="card"><label>파일 불러오기 · MD / TXT / CSV / XLSX<input type="file" id="file" accept=".md,.txt,.csv,.xlsx"></label><div class="grid"><label>파일명<input name="name" placeholder="업무기준.md" required></label><label>공유 범위<select name="scope"><option value="org">조직 공유</option><option value="private">나만 보기</option></select></label></div><label>원문<textarea name="content" rows="9" required></textarea></label><p class="muted">텍스트 256 KiB / XLSX 원본 2 MiB 이하 · Excel 수식은 실행하지 않습니다. 처음 등록한 기록은 초안입니다. 외부 도구 자동 연동은 제공하지 않습니다.</p><div class="actions"><button type="button" id="example">가상 예시 채우기</button><button class="primary">기록 등록</button></div></form>`;const f=$('#upload-form');$('#example').onclick=()=>{xlsxFile=null;f.content.disabled=false;f.elements.name.value='가상-충전기-식별자.md';f.content.value=example};$('#file').onchange=e=>run(null,async()=>{const file=e.target.files[0];if(!file)return;xlsxFile=null;f.content.disabled=false;if(/\.xlsx$/i.test(file.name)){if(file.size>2097152)throw Error('XLSX는 2 MiB 이하만 지원합니다.');xlsxFile=file;f.elements.name.value=file.name;f.content.value='Excel 원본은 서버에서 시트·셀 위치와 함께 추출합니다. 등록 후 원문을 확인하세요.';f.content.disabled=true;return}if(file.size>262144)throw Error('텍스트는 256 KiB 이하 파일을 선택하세요.');f.elements.name.value=file.name;f.content.value=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer())});f.onsubmit=e=>{e.preventDefault();if(!requireLogin())return;run(f.querySelector('.primary'),async()=>{let r;if(xlsxFile){const bytes=new Uint8Array(await xlsxFile.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));r=await api('/api/upload/xlsx',{name:f.elements.name.value,content_base64:btoa(binary),scope:f.scope.value})}else{r=await api('/api/upload',{name:f.elements.name.value,content:f.content.value,scope:f.scope.value})}await openDoc(r.id);notify('기록을 초안으로 등록했습니다.')})}}
async function openDoc(id,version){selected=await api('/api/docs/'+id);page='docs';document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));renderDetail(version)}
function renderDetail(version){const d=selected,v=d.versions.find(x=>x.version===version)||d.versions[0];$('#page').innerHTML=heading('SOURCE & REVIEW',esc(d.name),'원문 버전과 확인 이력을 함께 확인하세요.')+`<button id="back">← 기록 목록</button><div class="card"><div class="row">${badge(v.state)}<span class="muted">${esc(v.author)} · ${esc(v.created)} · ${d.scope==='private'?'나만 보기':'조직 공유'}</span></div><label>원문 버전<select id="version">${d.versions.map(x=>`<option value="${x.version}" ${x.version===v.version?'selected':''}>v${x.version} · ${esc(x.state)} · ${esc(x.reason)}</option>`).join('')}</select></label>${d.original?`<div class="notice">Excel 원본 보존 · ${esc(d.original.filename)} · ${d.original.size} bytes<br><small>SHA-256: ${esc(d.original.sha256)}</small><br><button id="download-original">원본 XLSX 다운로드</button></div>`:''}<pre class="source">${esc(v.content.split('\n').map((x,i)=>`${i+1}  ${v.source_cells?.find(c=>c.line===i+1)?'['+v.source_cells.find(c=>c.line===i+1).sheet+'!'+v.source_cells.find(c=>c.line===i+1).cell+'] ':''}${x}`).join('\n'))}</pre>${v.rule?`<p>등록 답변: ${esc(v.rule.answer)}</p><p class="muted">질문: ${esc(v.rule.question)} · 맥락: ${esc(v.rule.context)}<br>${esc(v.rule.valid_from)} ~ ${esc(v.rule.valid_to)} · 근거 ${v.rule.line}행</p>`:''}</div><div class="card"><h2>확인 요청과 처리 이력</h2>${d.comments.map(c=>`<div class="evidence">${badge(c.resolved_version?'처리 완료 · v'+c.resolved_version:'미확인 댓글')}<p>${esc(c.body)}</p><small>${esc(c.author)} · 원문 v${c.version} · #${c.id}</small>${c.resolved_version?`<p class="muted">${esc(c.resolved_by)}: ${esc(c.resolution_reason)}</p>`:''}</div>`).join('')||'<p class="muted">등록된 확인 요청이 없습니다.</p>'}<form id="comment-form"><label>v${v.version}에 확인 요청<textarea name="body" placeholder="어떤 맥락과 적용일에 확인이 필요한가요?" maxlength="4000" required></textarea></label><div class="actions"><button class="primary">댓글로 확인 요청</button></div></form></div>${user.role==='admin'?revisionForm(d):'<p class="muted">원문 확인·정정과 업무 답변 등록은 담당자(admin)가 수행합니다.</p>'}`;
if($('#download-original'))$('#download-original').onclick=e=>run(e.target,()=>downloadOriginal(d));$('#back').onclick=()=>run(null,loadDocs);$('#version').onchange=e=>renderDetail(Number(e.target.value));$('#comment-form').onsubmit=e=>{e.preventDefault();run(e.target.querySelector('button'),async()=>{await api(`/api/docs/${d.id}/comments`,{body:e.target.body.value,version:v.version});await openDoc(d.id,v.version);notify('확인 요청을 저장했습니다.')})};if($('#revise-form'))bindRevise(d)}
function revisionForm(d){return `<details class="card"><summary>담당자 확인·정정 · 현재 v${d.current} 기준</summary><form id="revise-form"><label>정정 원문<textarea name="content" rows="8" required>${esc(d.versions[0].content)}</textarea></label><div class="grid"><label>확인 상태<select name="state"><option>확인</option><option>정정</option><option>초안</option><option>거절</option></select></label><label>처리 이유<input name="reason" required></label></div><h3>이 정정으로 처리할 댓글</h3>${d.comments.filter(c=>!c.resolved_version).map(c=>`<label class="check"><input type="checkbox" name="resolve" value="${c.id}">#${c.id} ${esc(c.body)}</label>`).join('')||'<p class="muted">미처리 댓글 없음</p>'}<label class="check"><input type="checkbox" id="use-rule">다른 구성원이 재사용할 업무 답변 등록</label><fieldset id="rule-fields" disabled hidden><label>정확히 일치할 질문<input name="question" required></label><label>업무 맥락<input name="context" required></label><label>확인한 답변<textarea name="answer" required></textarea></label><div class="grid"><label>적용 시작<input type="date" name="valid_from" required></label><label>적용 종료<input type="date" name="valid_to" required></label></div><label>근거 원문 행<input type="number" name="line" min="1" value="2" required></label></fieldset><p class="muted">새 버전의 등록 답변을 생략하면 이전 버전의 답변은 검색에 재사용되지 않습니다.</p><div class="actions"><button type="button" id="reload-doc">최신 원문 조회</button><button class="primary">새 버전 저장</button></div></form></details>`}
function bindRevise(d){const f=$('#revise-form');$('#use-rule').onchange=e=>{$('#rule-fields').disabled=!e.target.checked;$('#rule-fields').hidden=!e.target.checked};$('#reload-doc').onclick=()=>{if(confirm('입력 중인 변경을 버리고 최신 원문을 조회할까요?'))run(null,()=>openDoc(d.id))};f.onsubmit=e=>{e.preventDefault();run(f.querySelector('.primary'),async()=>{const body={version:d.current,content:f.content.value,state:f.state.value,reason:f.reason.value,resolve_comments:[...f.querySelectorAll('[name=resolve]:checked')].map(x=>Number(x.value))};if($('#use-rule').checked)body.rule=Object.fromEntries(['question','context','answer','valid_from','valid_to','line'].map(k=>[k,k==='line'?Number(f.elements[k].value):f.elements[k].value]));await api(`/api/docs/${d.id}/revise`,body);await openDoc(d.id);notify('새 버전과 처리 이력을 저장했습니다.')})}}
$('nav').onclick=e=>{const b=e.target.closest('[data-page]');if(!b)return;page=b.dataset.page;notify('');render();if(page==='docs'&&user)run(null,loadDocs)};
$('#close-login').onclick=()=>$('#login').close();$('#session').onclick=()=>{if(!user)return openLogin();run($('#session'),async()=>{await api('/api/logout',{});sessionGeneration++;token='';user=null;docs=[];selected=null;connection();render();notify('로그아웃했습니다. 서버 세션을 폐기했습니다.')})};
$('#login-form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('.primary');b.disabled=true;try{sessionGeneration++;token='';user=null;docs=[];selected=null;connection();base=validBase(f.base.value);const r=await api('/api/login',{name:f.elements.name.value,password:f.password.value,auth:'bearer'});token=r.access_token;user=await api('/api/me');f.password.value='';$('#login').close();notify('');connection();render();if(page==='docs')await loadDocs()}catch(error){if(error instanceof StaleSessionError)return;sessionGeneration++;token='';user=null;connection();$('#login-error').textContent=error.message}finally{b.disabled=false}};
connection();render();

async function downloadOriginal(d){const generation=sessionGeneration;const response=await fetch(base+'/api/docs/'+d.id+'/original',{headers:{Authorization:'Bearer '+token},credentials:'omit'});if(generation!==sessionGeneration)throw new StaleSessionError();if(!response.ok)throw Error(response.status+' · 원본 다운로드 실패');const blob=await response.blob();if(generation!==sessionGeneration)throw new StaleSessionError();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=d.original.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
