'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sessionGeneration=0;
class StaleSessionError extends Error {}
let base=window.KNOWHOW_CONFIG?.apiBase||'', token='',user=null,page='explore',docs=[],selected=null,xlsxFile=null;
const example='가상 예시 — 실제 내부 자료나 정책이 아닙니다.\n고객 안내에는 CNUM을 사용합니다. 개발·통신 식별자는 modem_id입니다.\n대외 BID/SID/CID는 외부 시스템 식별자이며 내부 CNUM과 동일하다고 가정하지 않습니다.\n충전기 대조: 가상 CNUM EX-001 / modem_id MODEM-DEMO-01. 대외 ID와의 연결 관계 및 적용 기간은 미확인입니다.';
function badge(s){return `<span class="badge ${/상충|거절/.test(s)?'bad':/확인된|^확인$|^정정$/.test(s)?'good':'warn'}">${esc(s)}</span>`}
function notify(s){$('#message').textContent=s}
function connection(){ $('#connection').textContent=user?`${user.org} · ${user.name} · ${user.role==='admin'?'담당자':'구성원'} | API 연결: ${base}`:(base?`로그인 필요 · API 연결 대상: ${base}`:'API 미연결 · 서버 주소와 계정으로 로그인하면 기록을 조회하고 저장할 수 있습니다.');$('#session').textContent=user?'로그아웃':'API 연결'; }
function requireLogin(){if(!user){openLogin();return false}return true}
function openLogin(){$('#login-form').elements.base.value=base;$('#login-error').textContent='';$('#login').showModal()}
function validBase(value){const u=new URL(value);if(u.username||u.password||u.search||u.hash||!['/','/knowhow','/knowhow/'].includes(u.pathname)||!(u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname))))throw Error('HTTPS API 주소를 입력하세요. 경로는 /knowhow만 허용합니다. 로컬 호스트만 HTTP를 허용합니다.');return u.origin+(u.pathname.startsWith('/knowhow')?'/knowhow':'')}
async function api(path,data){const generation=sessionGeneration;const response=await fetch(base+path,{method:data===undefined?'GET':'POST',credentials:'omit',headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(60000)});if(generation!==sessionGeneration)throw new StaleSessionError();let body;try{body=await response.json()}catch{throw Error('API가 JSON 응답을 반환하지 않았습니다. 주소를 확인하세요.')}if(generation!==sessionGeneration)throw new StaleSessionError();if(!response.ok){if(response.status===401){sessionGeneration++;token='';user=null;docs=[];selected=null;clearWorkflow();connection();render()}throw Error(`${response.status} · ${body.error||'요청 실패'}${response.status===409?' 입력을 보관한 뒤 원문을 다시 조회하세요.':''}`)}return body}
async function run(button,task){if(button)button.disabled=true;notify('');try{await task()}catch(e){if(e instanceof StaleSessionError)return;notify(e.name==='TypeError'?'API 연결 실패 · 서버 주소, 실행 상태와 CORS 설정을 확인한 뒤 다시 시도하세요.':e.message)}finally{if(button)button.disabled=false}}
function heading(k,t,d){return `<div class="hero"><div class="eyebrow">${k}</div><h1>${t}</h1><p>${d}</p></div>`}
function newWorkflow(){return {query:'',searchQuery:'',searched:false,stations:[],searchTotal:0,searchMore:false,source:null,notice:'',station:null,chargers:[],chargerTotal:0,chargerMore:false,keys:[],question:'개발팀에 이 충전기의 내부 장비 정보와 연결 관계를 어떻게 확인하면 될까요?',inquiry:null,revision:0}}
let workflow=newWorkflow();
function clearWorkflow(){workflow=newWorkflow()}
function sourceMarkup(source){
 if(!source)return '<p class="muted">출처 정보가 제공되지 않았습니다.</p>';
 const url=source.source_url;let link='';try{const parsed=new URL(url);if(['https:','http:'].includes(parsed.protocol))link=`<a href="${esc(parsed.href)}" target="_blank" rel="noopener noreferrer">공개 데이터 출처 ↗</a>`}catch{}
 return `<div class="source-note">${link||'공개 데이터 출처'} · 수집 ${esc(source.collection_finished_at||source.collection_started_at||'시점 정보 없음')}<br><small>수집 당시 보관본입니다. 현재 운영·통신 상태와 내부 장비 매핑은 별도 확인이 필요합니다.</small></div>`;
}
function workflowContext(){const s=workflow.station;if(!s)return '';const chosen=workflow.chargers.filter(c=>workflow.keys.includes(c.record_key));return `선택 충전소: ${s.name}\n주소: ${s.address}\n운영사: ${s.operator}\n선택 공개 충전기 ID: ${chosen.map(c=>c.charger_id||'원문에 없음').join(', ')||'미선택'}\n내부 장비 ID 및 매핑: 미확인`}
function renderWorkflow(){
 const w=workflow,s=w.station;
 $('#page').innerHTML=heading('FROM PLACE TO ACTION','장소를 찾고, 다음 업무로 이어가세요','충전소를 구분하고 충전기를 확인한 뒤, 개발팀에 전달할 질문을 정리합니다.')+`
 <ol class="workflow-steps"><li class="active">1 장소 찾기</li><li class="${s?'active':''}">2 충전기 확인</li><li class="${w.inquiry?'active':''}">3 문의 정리</li></ol>
 <form id="place-form" class="card"><label>어디에 있는 충전소를 찾고 있나요?<input name="query" value="${esc(w.query)}" placeholder="GS타워에 있는 충전소명 뭐야?" maxlength="300" required></label><div class="actions"><button class="primary">충전소 찾기 →</button></div><p class="muted">장소명이나 주소로 검색하고, 운영사와 주소를 보고 업무 대상을 선택하세요.</p></form>
 ${w.searched?`<section class="card"><div class="row"><h2>충전소 후보</h2><span class="muted">${w.searchTotal}개 후보 · ${w.stations.length}개 표시</span></div><p class="muted">실제 검색어: ${esc(w.searchQuery)} · 장소명·주소 기준 후보이며 물리적 충전소 고유 ID가 아닙니다.</p><p>${esc(w.notice)}</p>${w.stations.map((x,i)=>`<button class="station-option ${s?.station_key===x.station_key?'chosen':''}" data-station="${i}" aria-pressed="${s?.station_key===x.station_key}"><strong>${esc(x.name)}</strong><span>${esc(x.address||'주소 없음')}</span><small>${esc(x.operator||'운영사 없음')} · 원문 ${x.row_count}행</small></button>`).join('')||'<p class="empty">일치하는 장소가 없습니다. 건물명 또는 도로명 주소로 다시 검색하세요. 없는 충전소나 ID는 추정하지 않습니다.</p>'}${w.searchMore?'<button id="more-stations">후보 더 보기</button>':''}${sourceMarkup(w.source)}</section>`:''}
 ${s?`<section class="card"><div class="eyebrow">SELECTED STATION</div><h2>${esc(s.name)}</h2><p>${esc(s.address)} · ${esc(s.operator)}</p><div class="notice">이 충전소를 기준으로 후속 질문을 이어갑니다. 다른 후보를 선택하면 충전기 선택과 문의 초안이 초기화됩니다.</div><h3>문의할 충전기를 선택하세요</h3><p class="muted">${w.chargerTotal}개 원본 행 · 공개 ID는 원문 그대로 표시합니다. 내부 장비 ID가 아닙니다.</p>${w.chargers.map((c,i)=>`<label class="charger-option"><input type="checkbox" data-charger="${i}" ${w.keys.includes(c.record_key)?'checked':''}><span><strong>공개 충전기 ID ${esc(c.charger_id||'원문에 없음')}</strong><small>${esc(c.type||'형식 정보 없음')} · 수집 당시 상태: ${esc(c.status||'정보 없음')}</small><small>${esc(c.location||'상세 위치 정보 없음')}</small><small>출처 원본 행: ${esc(c.source?.rowid??'정보 없음')}</small></span></label>`).join('')||'<p class="empty">표시할 충전기 원문이 없습니다.</p>'}${w.chargerMore?'<button id="more-chargers">충전기 더 보기</button>':''}${sourceMarkup(w.source)}<form id="inquiry-form"><label>개발팀에 확인하고 싶은 내용<textarea name="question" rows="3" required maxlength="2000">${esc(w.question)}</textarea></label><p class="muted">${w.keys.length}개 선택 · 장소·주소·운영사·공개 ID·출처와 함께 미확인 항목을 질문에 포함합니다.</p><div class="actions"><button class="primary" ${w.keys.length?'':'disabled'}>개발팀 문의 초안 만들기</button></div></form></section>`:''}
 ${w.inquiry?renderInquiry(w.inquiry):''}`;
 $('#place-form').onsubmit=e=>{e.preventDefault();workflow.query=e.target.query.value.trim();if(!requireLogin())return;run(e.target.querySelector('button'),()=>searchPlaces(false))};
 document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>run(b,()=>selectStation(Number(b.dataset.station))));
 document.querySelectorAll('[data-charger]').forEach(c=>c.onchange=()=>{const key=workflow.chargers[Number(c.dataset.charger)].record_key;workflow.question=$('#inquiry-form').question.value;workflow.keys=c.checked?[...workflow.keys,key]:workflow.keys.filter(x=>x!==key);workflow.inquiry=null;workflow.revision++;renderWorkflow()});
 if($('#more-stations'))$('#more-stations').onclick=e=>run(e.target,()=>searchPlaces(true));
 if($('#more-chargers'))$('#more-chargers').onclick=e=>run(e.target,()=>loadChargers(true));
 if($('#inquiry-form'))$('#inquiry-form').onsubmit=e=>{e.preventDefault();workflow.question=e.target.question.value.trim();run(e.target.querySelector('button'),createInquiry)};
 if($('#followup-form'))$('#followup-form').onsubmit=e=>{e.preventDefault();workflow.question=e.target.question.value.trim();run(e.target.querySelector('button'),createInquiry)};
 if($('#copy-inquiry'))$('#copy-inquiry').onclick=e=>run(e.target,async()=>{const draft=$('#draft').value;await navigator.clipboard.writeText(draft);notify('문의 초안을 복사했습니다. 내용을 확인한 뒤 직접 전달하세요.')});
 if($('#knowledge-followup'))$('#knowledge-followup').onclick=()=>{page='ask';render()};
}
async function searchPlaces(append){
 const q=workflow.query,offset=append?workflow.stations.length:0,revision=++workflow.revision;
 const r=await api('/api/workflow/search',{q,limit:20,offset});if(workflow.revision!==revision)return;
 workflow.stations=append?[...workflow.stations,...r.stations]:r.stations;workflow.searched=true;workflow.searchQuery=r.search_query||q;workflow.searchTotal=r.total;workflow.searchMore=r.has_more;workflow.source=r.source;workflow.notice=r.notice||'';
 if(!append){workflow.station=null;workflow.chargers=[];workflow.keys=[];workflow.inquiry=null}
 if(page==='explore')renderWorkflow();
}
async function selectStation(index){workflow.station=workflow.stations[index];workflow.chargers=[];workflow.keys=[];workflow.inquiry=null;workflow.chargerMore=false;workflow.chargerTotal=0;workflow.revision++;renderWorkflow();await loadChargers(false)}
async function loadChargers(append){const stationKey=workflow.station.station_key,revision=++workflow.revision;const r=await api('/api/workflow/chargers',{station_key:stationKey,limit:50,offset:append?workflow.chargers.length:0});if(workflow.revision!==revision)return;workflow.station=r.station;workflow.chargers=append?[...workflow.chargers,...r.chargers]:r.chargers;workflow.chargerTotal=r.total;workflow.chargerMore=r.has_more;workflow.source=r.source;if(page==='explore')renderWorkflow()}
async function createInquiry(){if(!workflow.station||!workflow.keys.length)throw Error('충전소와 문의할 충전기를 선택하세요.');const revision=++workflow.revision;const r=await api('/api/workflow/inquiry',{station_key:workflow.station.station_key,record_keys:[...workflow.keys],question:workflow.question});if(workflow.revision!==revision)return;workflow.inquiry=r;if(page==='explore')renderWorkflow()}
function renderInquiry(r){return `<section class="card inquiry"><div class="eyebrow">READY TO REVIEW</div><h2>개발팀에 이렇게 물어보세요</h2><p>선택한 자료로 정리한 문의 초안입니다. 자동 전송되지 않습니다.</p><div class="grid"><div><h3>원문에서 확인한 정보</h3><ul>${(r.verified||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h3>추가 확인이 필요한 정보</h3><ul>${(r.unverified||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><label>전달할 문의 내용<textarea id="draft" rows="13">${esc(r.draft)}</textarea></label><div class="actions"><button id="knowledge-followup">관련 업무 기록 찾기</button><button id="copy-inquiry" class="primary">초안 복사</button></div>${sourceMarkup(r.source)}<form id="followup-form"><label>같은 장소·충전기에 대해 이어서 질문<input name="question" placeholder="통신이 안 되는 경우 어떤 로그를 함께 전달해야 할까?" required maxlength="2000"></label><div class="actions"><button>선택 맥락으로 초안 다시 만들기</button></div></form></section>`}

function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='explore')renderWorkflow();if(page==='ask')renderAsk();if(page==='docs')renderDocs();if(page==='upload')renderUpload()}
function renderAsk(){$('#page').innerHTML=heading('KNOWLEDGE SEARCH','업무 기록에서 근거를 찾아보세요','원문과 확인 이력을 살펴보고, 담당자에게 필요한 내용을 질문하세요.')+`${workflow.station?`<div class="notice">${esc(workflowContext())}<br><button id="return-workflow">← 장소 업무로 돌아가기</button></div>`:''}<form id="ask-form" class="card"><label>업무 질문<textarea name="question" placeholder="선택한 충전기의 내부 장비 정보를 확인하려면 어떤 자료가 필요한가요?" required maxlength="1000"></textarea></label><div class="grid"><label>업무 맥락<input name="context" value="${esc(workflowContext().replace(/\n/g,' · '))}" placeholder="업무 맥락" required></label><label>적용일<input name="as_of" type="date" value="${new Date().toLocaleDateString('en-CA')}" required></label></div><label class="check"><input type="checkbox" name="generate"> AI 설명 요청 · 모델 연결 시에도 미확인 초안</label><div class="actions"><button class="primary">근거 찾기 →</button></div><p class="muted">담당자 등록 답변은 질문·맥락·기간이 일치할 때 재사용됩니다.</p></form><div id="result" aria-live="polite"></div>`;
if($('#return-workflow'))$('#return-workflow').onclick=()=>{page='explore';render()};$('#ask-form').onsubmit=e=>{e.preventDefault();if(!requireLogin())return;const f=e.target;run(f.querySelector('button'),async()=>{const r=await api('/api/ask',{question:f.question.value.trim(),context:f.context.value.trim(),as_of:f.as_of.value,generate:f.generate.checked});$('#result').innerHTML=`<div class="card">${badge(r.status)}<p class="muted">${esc(r.mode)}</p><div class="answer">${esc(r.answer||r.notice||'생성된 답변이 없습니다. 원문 근거를 확인하세요.')}</div><p class="muted">${r.answerable?'담당자가 등록한 답변입니다. 아래 출처와 적용 기간을 함께 확인하세요.':'확정 답변으로 사용하지 마세요. 원문을 열어 담당자에게 확인을 요청할 수 있습니다.'}</p>${renderEvidence(r)}</div>`;bindOpen()})}}

function evidenceKey(x){return [x.id,x.version,x.line??'',x.comment_id??''].join(':')}
function evidenceCard(x,history=false){
 const rule=x.rule||{}, context=rule.context||x.context, from=rule.valid_from||x.valid_from, to=rule.valid_to||x.valid_to;
 const usage=x.applicability;
 const scopeLabel=history?'현재 적용 불가 · 이력 참고':usage==='applicable'?'요청 범위에 적용 가능':'적용 범위 미확인';
 return `<div class="evidence"><div class="row"><strong>${esc(x.name)}</strong>${badge(x.state)}</div>
 <p>${badge(scopeLabel)}</p>
 ${x.applicability_reasons?.length?`<p class="scope-reason">적용 불가 사유: ${x.applicability_reasons.map(esc).join(' · ')}</p>`:''}
 <p>${esc(x.text)}</p><p class="muted">v${esc(x.version)} · ${esc(x.location)}${x.source?' · '+esc(x.source.sheet)+'!'+esc(x.source.cell):''}</p>
 <p class="muted">업무 맥락: ${esc(context||'미등록')} · 적용 기간: ${from?esc(from)+' ~ '+esc(to):'미등록'}<br>확인자 / 작성자: ${esc(x.reviewer||'정보 없음')}${x.reason?' · 처리 이유: '+esc(x.reason):''}</p>
 <button data-open="${esc(x.id)}" data-version="${esc(x.version)}">원문과 확인 요청 →</button></div>`;
}
function renderEvidence(r){
 const history=new Map();
 for(const x of [...(r.evidence||[]).filter(x=>x.applicability==='history_only'),...(r.historical_evidence||[])])history.set(evidenceKey(x),x);
 const current=(r.evidence||[]).filter(x=>x.applicability!=='history_only'&&!history.has(evidenceKey(x)));
 return current.map(x=>evidenceCard(x)).join('')+(history.size?`<section class="history-evidence"><h3>이력 참고 · 현재 답변에 적용하지 않음</h3><p class="muted">요청한 업무 맥락이나 적용일에 맞지 않는 자료입니다. 확인된 원문이어도 현재 업무 기준으로 사용하지 마세요.</p>${[...history.values()].map(x=>evidenceCard(x,true)).join('')}</section>`:'')||'<p class="empty">표시할 근거가 없습니다. 기록을 입수하거나 질문을 바꿔보세요.</p>';
}

function bindOpen(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>run(b,()=>openDoc(Number(b.dataset.open),Number(b.dataset.version)||undefined)))}
async function loadDocs(){if(!requireLogin())return;docs=(await api('/api/docs')).docs;renderDocs()}
function renderDocs(){$('#page').innerHTML=heading('KNOWLEDGE LIBRARY','지식 기록','원문부터 확인 이력까지, 팀이 함께 쌓아가는 업무 지식입니다.')+`<div class="row"><span class="muted">${user?docs.length+'개의 접근 가능한 기록':'로그인 후 기록을 조회하세요.'}</span><button id="refresh">새로고침</button></div>${docs.map(d=>`<button class="doc" data-open="${d.id}"><span><strong>${esc(d.name)}</strong><small>${d.scope==='private'?'나만 보기':'조직 공유'} · v${d.current}</small></span>${badge(d.state)}</button>`).join('')||'<div class="card empty">아직 표시할 기록이 없습니다. MD·TXT·CSV 원문을 직접 등록하세요.</div>'}`;$('#refresh').onclick=e=>run(e.target,loadDocs);bindOpen()}
function renderUpload(){xlsxFile=null;$('#page').innerHTML=heading('CAPTURE KNOWLEDGE','흩어진 기록을 한곳으로','원문을 등록하고, 확인이 필요한 내용을 팀과 함께 정리하세요.')+`<form id="upload-form" class="card"><label>파일 불러오기 · MD / TXT / CSV / XLSX<input type="file" id="file" accept=".md,.txt,.csv,.xlsx"></label><div class="grid"><label>파일명<input name="name" placeholder="업무기준.md" required></label><label>공유 범위<select name="scope"><option value="org">조직 공유</option><option value="private">나만 보기</option></select></label></div><label>원문<textarea name="content" rows="9" required></textarea></label><p class="muted">텍스트 256 KiB / XLSX 원본 2 MiB 이하 · Excel 수식은 실행하지 않습니다. 처음 등록한 기록은 초안입니다. 외부 도구 자동 연동은 제공하지 않습니다.</p><div class="actions"><button type="button" id="example">가상 예시 채우기</button><button class="primary">기록 등록</button></div></form>`;const f=$('#upload-form');$('#example').onclick=()=>{xlsxFile=null;f.content.disabled=false;f.elements.name.value='가상-충전기-식별자.md';f.content.value=example};$('#file').onchange=e=>run(null,async()=>{const file=e.target.files[0];if(!file)return;xlsxFile=null;f.content.disabled=false;if(/\.xlsx$/i.test(file.name)){if(file.size>2097152)throw Error('XLSX는 2 MiB 이하만 지원합니다.');xlsxFile=file;f.elements.name.value=file.name;f.content.value='Excel 원본은 서버에서 시트·셀 위치와 함께 추출합니다. 등록 후 원문을 확인하세요.';f.content.disabled=true;return}if(file.size>262144)throw Error('텍스트는 256 KiB 이하 파일을 선택하세요.');f.elements.name.value=file.name;f.content.value=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer())});f.onsubmit=e=>{e.preventDefault();if(!requireLogin())return;run(f.querySelector('.primary'),async()=>{let r;if(xlsxFile){const bytes=new Uint8Array(await xlsxFile.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));r=await api('/api/upload/xlsx',{name:f.elements.name.value,content_base64:btoa(binary),scope:f.scope.value})}else{r=await api('/api/upload',{name:f.elements.name.value,content:f.content.value,scope:f.scope.value})}await openDoc(r.id);notify('기록을 초안으로 등록했습니다.')})}}
async function openDoc(id,version){selected=await api('/api/docs/'+id);page='docs';document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));renderDetail(version)}
function renderDetail(version){const d=selected,v=d.versions.find(x=>x.version===version)||d.versions[0];$('#page').innerHTML=heading('SOURCE & REVIEW',esc(d.name),'원문 버전과 확인 이력을 함께 확인하세요.')+`<button id="back">← 기록 목록</button><div class="card"><div class="row">${badge(v.state)}<span class="muted">${esc(v.author)} · ${esc(v.created)} · ${d.scope==='private'?'나만 보기':'조직 공유'}</span></div><label>원문 버전<select id="version">${d.versions.map(x=>`<option value="${x.version}" ${x.version===v.version?'selected':''}>v${x.version} · ${esc(x.state)} · ${esc(x.reason)}</option>`).join('')}</select></label>${d.original?`<div class="notice">Excel 원본 보존 · ${esc(d.original.filename)} · ${d.original.size} bytes<br><small>SHA-256: ${esc(d.original.sha256)}</small><br><button id="download-original">원본 XLSX 다운로드</button></div>`:''}<pre class="source">${esc(v.content.split('\n').map((x,i)=>`${i+1}  ${v.source_cells?.find(c=>c.line===i+1)?'['+v.source_cells.find(c=>c.line===i+1).sheet+'!'+v.source_cells.find(c=>c.line===i+1).cell+'] ':''}${x}`).join('\n'))}</pre>${v.rule?`<p>등록 답변: ${esc(v.rule.answer)}</p><p class="muted">질문: ${esc(v.rule.question)} · 맥락: ${esc(v.rule.context)}<br>${esc(v.rule.valid_from)} ~ ${esc(v.rule.valid_to)} · 근거 ${v.rule.line}행</p>`:''}</div><div class="card"><h2>확인 요청과 처리 이력</h2>${d.comments.map(c=>`<div class="evidence">${badge(c.resolved_version?'처리 완료 · v'+c.resolved_version:'미확인 댓글')}<p>${esc(c.body)}</p><small>${esc(c.author)} · 원문 v${c.version} · #${c.id}</small>${c.resolved_version?`<p class="muted">${esc(c.resolved_by)}: ${esc(c.resolution_reason)}</p>`:''}</div>`).join('')||'<p class="muted">등록된 확인 요청이 없습니다.</p>'}<form id="comment-form"><label>v${v.version}에 확인 요청<textarea name="body" placeholder="어떤 맥락과 적용일에 확인이 필요한가요?" maxlength="4000" required></textarea></label><div class="actions"><button class="primary">댓글로 확인 요청</button></div></form></div>${user.role==='admin'?revisionForm(d):'<p class="muted">원문 확인·정정과 업무 답변 등록은 담당자(admin)가 수행합니다.</p>'}`;
if($('#download-original'))$('#download-original').onclick=e=>run(e.target,()=>downloadOriginal(d));$('#back').onclick=()=>run(null,loadDocs);$('#version').onchange=e=>renderDetail(Number(e.target.value));$('#comment-form').onsubmit=e=>{e.preventDefault();run(e.target.querySelector('button'),async()=>{await api(`/api/docs/${d.id}/comments`,{body:e.target.body.value,version:v.version});await openDoc(d.id,v.version);notify('확인 요청을 저장했습니다.')})};if($('#revise-form'))bindRevise(d)}
function revisionForm(d){return `<details class="card"><summary>담당자 확인·정정 · 현재 v${d.current} 기준</summary><form id="revise-form"><label>정정 원문<textarea name="content" rows="8" required>${esc(d.versions[0].content)}</textarea></label><div class="grid"><label>확인 상태<select name="state"><option>확인</option><option>정정</option><option>초안</option><option>거절</option></select></label><label>처리 이유<input name="reason" required></label></div><h3>이 정정으로 처리할 댓글</h3>${d.comments.filter(c=>!c.resolved_version).map(c=>`<label class="check"><input type="checkbox" name="resolve" value="${c.id}">#${c.id} ${esc(c.body)}</label>`).join('')||'<p class="muted">미처리 댓글 없음</p>'}<label class="check"><input type="checkbox" id="use-rule">다른 구성원이 재사용할 업무 답변 등록</label><fieldset id="rule-fields" disabled hidden><label>정확히 일치할 질문<input name="question" required></label><label>업무 맥락<input name="context" required></label><label>확인한 답변<textarea name="answer" required></textarea></label><div class="grid"><label>적용 시작<input type="date" name="valid_from" required></label><label>적용 종료<input type="date" name="valid_to" required></label></div><label>근거 원문 행<input type="number" name="line" min="1" value="2" required></label></fieldset><p class="muted">새 버전의 등록 답변을 생략하면 이전 버전의 답변은 검색에 재사용되지 않습니다.</p><div class="actions"><button type="button" id="reload-doc">최신 원문 조회</button><button class="primary">새 버전 저장</button></div></form></details>`}
function bindRevise(d){const f=$('#revise-form');$('#use-rule').onchange=e=>{$('#rule-fields').disabled=!e.target.checked;$('#rule-fields').hidden=!e.target.checked};$('#reload-doc').onclick=()=>{if(confirm('입력 중인 변경을 버리고 최신 원문을 조회할까요?'))run(null,()=>openDoc(d.id))};f.onsubmit=e=>{e.preventDefault();run(f.querySelector('.primary'),async()=>{const body={version:d.current,content:f.content.value,state:f.state.value,reason:f.reason.value,resolve_comments:[...f.querySelectorAll('[name=resolve]:checked')].map(x=>Number(x.value))};if($('#use-rule').checked)body.rule=Object.fromEntries(['question','context','answer','valid_from','valid_to','line'].map(k=>[k,k==='line'?Number(f.elements[k].value):f.elements[k].value]));await api(`/api/docs/${d.id}/revise`,body);await openDoc(d.id);notify('새 버전과 처리 이력을 저장했습니다.')})}}
$('nav').onclick=e=>{const b=e.target.closest('[data-page]');if(!b)return;page=b.dataset.page;notify('');render();if(page==='docs'&&user)run(null,loadDocs)};
$('#close-login').onclick=()=>$('#login').close();$('#session').onclick=()=>{if(!user)return openLogin();run($('#session'),async()=>{await api('/api/logout',{});sessionGeneration++;token='';user=null;docs=[];selected=null;clearWorkflow();connection();render();notify('로그아웃했습니다. 서버 세션을 폐기했습니다.')})};
$('#login-form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('.primary');b.disabled=true;const pendingQuery=workflow.query;try{sessionGeneration++;token='';user=null;docs=[];selected=null;clearWorkflow();workflow.query=pendingQuery;connection();base=validBase(f.base.value);const r=await api('/api/login',{name:f.elements.name.value,password:f.password.value,auth:'bearer'});token=r.access_token;user=await api('/api/me');f.password.value='';$('#login').close();notify('');connection();render();if(page==='docs')await loadDocs()}catch(error){if(error instanceof StaleSessionError)return;sessionGeneration++;token='';user=null;connection();$('#login-error').textContent=error.message}finally{b.disabled=false}};
connection();render();

async function downloadOriginal(d){const generation=sessionGeneration;const response=await fetch(base+'/api/docs/'+d.id+'/original',{headers:{Authorization:'Bearer '+token},credentials:'omit'});if(generation!==sessionGeneration)throw new StaleSessionError();if(!response.ok)throw Error(response.status+' · 원본 다운로드 실패');const blob=await response.blob();if(generation!==sessionGeneration)throw new StaleSessionError();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=d.original.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
