'use strict';
// Public read-only fixture API and browser-only KB. Never receives an org token.
const sampleDemo=(()=>{
 const storageKey='knowhow.public-sample-kb.v1';
 let active=false,epoch=0,state=fresh();
 function fresh(){return {q:'',id:'',stations:[],searched:false,total:0,offset:0,source:null,notice:'',station:null,chargers:[],keys:[],department:'app',question:'앱에서 확인할 ID와 문의 시 전달할 내용을 알려주세요.',inquiry:null,current:null,view:'search',kbDepartment:''}}
 function read(){try{const value=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(value))throw Error();return value}catch{throw Error('브라우저 샘플 KB를 읽을 수 없습니다. 브라우저 저장 권한을 확인하세요.')}}
 function write(rows){try{localStorage.setItem(storageKey,JSON.stringify(rows))}catch{throw Error('브라우저 저장 공간에 기록하지 못했습니다. 저장 권한과 여유 공간을 확인하세요.')}}
 function scope(){return '<div class="notice">샘플 체험 · 공개 데이터 50행과 가상 부서 ID를 사용합니다. KB는 이 브라우저에만 저장되며 조직에 공유되지 않습니다. 브라우저 데이터를 삭제하면 사라집니다.</div>'}
 function targetKey(){return JSON.stringify([state.station.station_key,[...state.keys].sort(),state.department])}
 async function request(action,body){const generation=epoch;const response=await fetch((window.KNOWHOW_CONFIG?.apiBase||'https://api.ctrl-j.xyz/knowhow')+'/demo/workflow/'+action,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});const result=await response.json();if(!active||epoch!==generation)throw new StaleSessionError();if(!response.ok)throw Error(result.error||'샘플 요청에 실패했습니다. 잠시 후 다시 시도하세요.');return result}
 function activate(){sessionGeneration++;token='';user=null;docs=[];selected=null;clearWorkflow();active=true;epoch++;state=fresh();document.querySelector('nav').hidden=true;$('#connection').textContent='로그인 없는 샘플 체험 · 조직 업무 공간과 분리됨';$('#session').textContent='조직 로그인';render()}
 function deactivate(){active=false;epoch++;state=fresh();document.querySelector('nav').hidden=false;page='explore';connection();}
 function mount(content){$('#page').innerHTML=heading('TRY KNOW:HOW','샘플로 체험','충전소 찾기 → 부서 문의 가이드 → KB 저장 → 정정한 지식 재사용')+scope()+`<div class="actions"><button id="demo-search-nav">충전소 찾기</button><button id="demo-kb-nav">이 브라우저의 샘플 KB</button><button id="demo-exit">조직 업무 공간으로</button></div>`+content;$('#demo-exit').onclick=()=>{deactivate();restoreOrganizationView()};$('#demo-search-nav').onclick=()=>{epoch++;state.view='search';render()};$('#demo-kb-nav').onclick=()=>run(null,()=>{epoch++;state.view='list';render()})}
 function render(){if(!active)return;if(state.view==='list')return list();if(state.view==='detail')return detail();searchView()}
 function searchView(){const s=state;mount(`<form class="card" id="demo-search"><label>지역·주소·건물명<input name="q" value="${esc(s.q)}" placeholder="GS타워, 서울 강남구, 논현로 508" maxlength="300"></label><label>환경부 충전기 ID (선택)<input name="charger" value="${esc(s.id)}" placeholder="예: 01" maxlength="100"></label><p>ID를 몰라도 주소나 건물명으로 찾을 수 있습니다.</p><div class="actions"><button class="primary">충전소 찾기</button><button type="button" data-demo-example="GS타워">GS타워</button><button type="button" data-demo-example="서울 강남구 논현로 508">서울 강남구 · 논현로 508</button><button type="button" data-demo-example="GS타워" data-demo-id="01">GS타워 · 충전기 ID 01</button></div><p class="muted">50행 일부 데이터입니다. 검색되지 않는 지역은 미수록되었을 수 있습니다. ID 01만 입력하면 여러 후보가 나올 수 있습니다.</p></form>${s.searched?`<section class="card"><h2>충전소 후보 · ${s.total}개</h2><p>${esc(s.notice)}</p>${s.stations.map((x,i)=>`<button class="station-option ${s.station?.station_key===x.station_key?'chosen':''}" data-demo-station="${i}"><strong>${esc(x.name)}</strong><span>${esc(x.address)}</span><small>${esc(x.operator)} · ${x.row_count}행</small></button>`).join('')||'<p>이 샘플 범위에 일치하는 결과가 없습니다. GS타워 예시로 체험해 보세요.</p>'}${s.stations.length<s.total?'<button id="demo-more">후보 더 보기</button>':''}${sourceMarkup(s.source)}</section>`:''}${s.station?`<section class="card"><h2>${esc(s.station.name)}</h2><p>${esc(s.station.address)} · ${esc(s.station.operator)}</p><h3>문의할 충전기를 선택하세요</h3>${s.chargers.map((x,i)=>`<label class="charger-option"><input type="checkbox" data-demo-charger="${i}" ${s.keys.includes(x.record_key)?'checked':''}><span><strong>환경부 충전기 ID ${esc(x.charger_id)}</strong><small>${esc(x.type)} · ${esc(x.location)}</small></span></label>`).join('')}<form id="demo-inquiry"><label>문의 부서<select name="department"><option value="app" ${s.department==='app'?'selected':''}>앱개발팀</option><option value="device" ${s.department==='device'?'selected':''}>충전기개발팀</option></select></label><label>문의할 내용<textarea name="question" required maxlength="2000">${esc(s.question)}</textarea></label><button class="primary" ${s.keys.length?'':'disabled'}>부서 문의 가이드 만들기</button></form></section>`:''}${s.inquiry?inquiryMarkup():''}`);
 $('#demo-search').onsubmit=e=>{e.preventDefault();s.q=e.target.q.value.trim();s.id=e.target.charger.value.trim();run(e.target.querySelector('button'),()=>search(false))};document.querySelectorAll('[data-demo-example]').forEach(b=>b.onclick=()=>{const f=$('#demo-search');f.q.value=b.dataset.demoExample;f.charger.value=b.dataset.demoId||'';f.requestSubmit()});document.querySelectorAll('[data-demo-station]').forEach(b=>b.onclick=()=>run(b,()=>select(Number(b.dataset.demoStation))));document.querySelectorAll('[data-demo-charger]').forEach(c=>c.onchange=()=>{rememberForm();epoch++;const key=s.chargers[Number(c.dataset.demoCharger)].record_key;s.keys=c.checked?[...s.keys,key]:s.keys.filter(x=>x!==key);s.inquiry=null;s.current=null;render()});if($('#demo-more'))$('#demo-more').onclick=e=>run(e.target,()=>search(true));if($('#demo-inquiry')){$('#demo-inquiry').department.onchange=()=>{rememberForm();epoch++;s.inquiry=null;s.current=null;render()};$('#demo-inquiry').onsubmit=e=>{e.preventDefault();rememberForm();run(e.target.querySelector('button'),inquire)}}if($('#demo-save'))$('#demo-save').onclick=e=>run(e.target,save);if($('#demo-open'))$('#demo-open').onclick=()=>{s.view='detail';render()};if($('#demo-copy'))$('#demo-copy').onclick=e=>run(e.target,async()=>{await navigator.clipboard.writeText($('#demo-draft').value);notify('샘플 문의 내용을 복사했습니다.')});document.querySelectorAll('[data-demo-reuse]').forEach(b=>b.onclick=()=>run(b,()=>reuse(b.dataset.demoReuse)));
 }
 function rememberForm(){const f=$('#demo-inquiry');if(f){state.department=f.department.value;state.question=f.question.value.trim()}}
 async function search(append){if(!state.q&&!state.id)throw Error('주소·건물명 또는 충전기 ID를 입력하세요.');epoch++;const r=await request('search',{q:state.q,charger_id:state.id,limit:20,offset:append?state.stations.length:0});state.stations=append?[...state.stations,...r.stations]:r.stations;state.total=r.total;state.source=r.source;state.notice=r.notice||'';state.searched=true;if(!append){state.station=null;state.chargers=[];state.keys=[];state.inquiry=null;state.current=null}render()}
 async function select(index){epoch++;const station=state.stations[index];state.station=null;state.inquiry=null;state.current=null;state.keys=[];render();const r=await request('chargers',{station_key:station.station_key,limit:50,offset:0});state.station=r.station;state.chargers=r.chargers;state.source=r.source;render()}
 async function inquire(){epoch++;const r=await request('inquiry',{station_key:state.station.station_key,record_keys:state.keys,department:state.department,question:state.question});state.inquiry=r;state.current=null;const matches=read().filter(d=>d.target===targetKey());if(matches.length===1)applySaved(matches[0]);else if(matches.length>1)state.inquiry.candidates=matches.map(d=>({id:d.id,name:d.name,version:d.versions[0].version,state:d.versions[0].state}));render()}
 function applySaved(d){const v=d.versions[0];state.current=d.id;state.inquiry={...state.inquiry,draft:v.content+'\n\n이번 후속 문의: '+state.question,guide:v.version>1?[]:(d.inquiry.guide||[]),synthetic_mapping:v.version>1?[]:(d.inquiry.synthetic_mapping||[]),identifiers:v.version>1?[]:(d.inquiry.identifiers||[]),savedVersion:v.version,savedState:v.state,candidates:null,corrected:v.version>1}}
 function reuse(id){const d=read().find(x=>x.id===id&&x.target===targetKey());if(!d)throw Error('저장한 샘플을 찾지 못했습니다.');applySaved(d);render()}
 function inquiryMarkup(){const r=state.inquiry;if(r.candidates)return `<section class="card"><h2>재사용할 샘플 KB 선택</h2>${r.candidates.map(d=>`<p>${esc(d.name)} · v${d.version} · ${esc(d.state)} <button data-demo-reuse="${d.id}">이 KB 재사용</button></p>`).join('')}</section>`;return `<section class="card"><h2>${departmentName(state.department)} 문의 가이드</h2>${r.savedVersion?`<div class="notice">이 브라우저의 샘플 KB 재사용 · v${r.savedVersion} · ${esc(r.savedState)}</div>`:''}${r.corrected?'<p class="scope-reason">정정된 최신 본문을 재사용합니다. 이전 구조화 ID는 현재 관계로 표시하지 않습니다.</p>':mappingMarkup(r.identifiers||r.synthetic_mapping||[])}<h3>추가 확인할 정보</h3><ul>${(r.unverified||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${r.guide?.length?`<ol>${r.guide.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:''}<label>문의 초안<textarea id="demo-draft" rows="12" readonly>${esc(r.draft)}</textarea></label><div class="actions"><button id="demo-copy">초안 복사</button>${state.current?'<button id="demo-open" class="primary">저장된 샘플 KB 열기 · 정정</button>':'<button id="demo-save" class="primary">이 브라우저에 샘플 KB 저장</button>'}</div>${sourceMarkup(r.source)}<p class="muted">실제 부서로 전송하거나 조직 서버에 저장하지 않습니다.</p></section>`}
 function save(){if(state.current)return;const rows=read(),id=crypto.randomUUID(),r=state.inquiry;const d={id,target:targetKey(),name:state.station.name+' · '+departmentName(state.department),department:state.department,station:state.station,keys:[...state.keys],inquiry:r,versions:[{version:1,state:'초안',content:r.draft,reason:'샘플 체험에서 저장',created:new Date().toISOString()}]};write([...rows,d]);state.current=id;state.view='detail';render();notify('이 브라우저에만 샘플 KB를 저장했습니다.')}
 function list(){const rows=read().filter(d=>!state.kbDepartment||d.department===state.kbDepartment);mount(`<section class="card"><h2>이 브라우저의 샘플 KB · ${rows.length}건</h2><label>부서별로 보기<select id="demo-kb-department"><option value="">전체 부서</option><option value="app" ${state.kbDepartment==='app'?'selected':''}>앱개발팀</option><option value="device" ${state.kbDepartment==='device'?'selected':''}>충전기개발팀</option></select></label>${rows.map(d=>`<article class="evidence"><h3>${esc(d.name)}</h3><p>v${d.versions[0].version} · ${badge(d.versions[0].state)} · 브라우저 저장</p><button data-demo-doc="${d.id}">샘플 KB 열기 · 정정</button></article>`).join('')||'<p>아직 저장한 샘플이 없습니다. 충전소를 찾아 문의 가이드를 저장하세요.</p>'}</section>`);$('#demo-kb-department').onchange=e=>{state.kbDepartment=e.target.value;run(null,render)};document.querySelectorAll('[data-demo-doc]').forEach(b=>b.onclick=()=>{state.current=b.dataset.demoDoc;state.view='detail';run(b,render)})}
 function detail(){const d=read().find(x=>x.id===state.current);if(!d)throw Error('샘플 KB를 찾을 수 없습니다.');const v=d.versions[0];mount(`<section class="card"><h2>${esc(d.name)}</h2><p>v${v.version} · ${badge(v.state)} · 이 브라우저에만 저장</p><pre class="source">${esc(v.content)}</pre>${sourceMarkup(d.inquiry.source)}<form id="demo-revise"><h3>샘플 KB 정정</h3><p class="muted">샘플의 버전 갱신을 체험합니다. 실제 담당자 확인을 의미하지 않습니다.</p><label>정정할 본문<textarea name="content" rows="10" required maxlength="20000">${esc(v.content)}</textarea></label><label>정정 이유<input name="reason" required maxlength="500" placeholder="예: 문의 시 오류코드도 함께 전달"></label><button class="primary">새 버전으로 정정 저장</button></form><button id="demo-reask">이 대상·부서로 다시 질문하기</button><details><summary>버전 이력 (${d.versions.length})</summary>${d.versions.map(x=>`<article><h3>v${x.version} · ${esc(x.state)}</h3><p>${esc(x.reason)} · ${esc(x.created)}</p><pre class="source">${esc(x.content)}</pre></article>`).join('')}</details></section>`);$('#demo-revise').onsubmit=e=>{e.preventDefault();const f=e.target;run(f.querySelector('button'),()=>{const rows=read(),latest=rows.find(x=>x.id===d.id);if(latest.versions[0].version!==v.version)throw Error('다른 탭에서 수정되었습니다. 샘플 KB 목록에서 최신 버전을 다시 열어주세요.');latest.versions.unshift({version:v.version+1,state:'정정',content:f.content.value,reason:f.reason.value,created:new Date().toISOString()});write(rows);render();notify('정정한 샘플 KB를 새 버전으로 저장했습니다.')})};$('#demo-reask').onclick=e=>run(e.target,async()=>{epoch++;const r=await request('chargers',{station_key:d.station.station_key,limit:50,offset:0});state.station=r.station;state.chargers=r.chargers;state.keys=d.keys;state.department=d.department;state.view='search';await inquire()})}
 return {activate,deactivate,isActive:()=>active};
})();
