'use strict';
// Company workflow: one selected charger and one server document throughout.
const sampleDemo=(()=>{
 const fixture=window.KNOWHOW_EXAMPLE,legacyKey='knowhow.scenarios.v1';
 const apiBase=(window.KNOWHOW_CONFIG?.apiBase||'https://api.ctrl-j.xyz/knowhow').replace(/\/$/,'');
 const sessionKey='knowhow.company.session.v2:'+apiBase;
 const tabs=['문의할 대상 찾기','부서 문서 확인','댓글과 기준 정정','다음 사람이 조회','부서 KB 모음'];
 const dept=d=>d==='device'?'충전기개발팀':'앱개발팀',copy=v=>JSON.parse(JSON.stringify(v));
 const defaultQuestion=department=>`이 충전기의 ${department==='device'?'장비 이상은':'앱 오류는'} 누구에게 어떤 정보를 전달해야 하나요?`;
 const status=s=>({draft:'버전 검토 전',confirmed:'서버 확인 상태',rejected:'반려'}[s]||s);
 let active=false,generation=0,sourceView=null,sharingView=null,live=null,demoSnapshot=null,handoffSerial=0;
 const liveRoute=()=>/^#scenario-[1-5]-live$/.test(location.hash);
 const state={tab:1,busy:false,error:'',notice:'',session:null,expired:false,department:'app',station:copy(fixture.station),chargers:copy(fixture.chargers),recordKey:fixture.selected_record_key,source:copy(fixture.source),q:'GS타워',chargerId:'01',stations:[copy(fixture.station)],total:1,document:null,documents:[],loaded:false,role:'member',question:defaultQuestion('app'),asOf:'2026-09-21',answerMode:'knowledge',answer:null,answerQuestion:'',draft:null,comparison:null,comparisonError:'',commentDraft:'',humanDraft:null,revisionDraft:null};
 class Obsolete extends Error {}
 function charger(){return state.chargers.find(c=>c.record_key===state.recordKey)}
 function context(){return [state.station?.station_key,state.recordKey,state.department].join('|')}
 function matches(d){const s=d.source;if(live)return s?.kind==='data-platform-guide'&&s.context_id===live.context.context_id&&s.dataset_id===live.context.dataset_id&&d.department===live.context.department;return s?.kind==='company_charger_knowledge'&&s.station?.station_key===state.station?.station_key&&s.record_key===state.recordKey&&d.department===state.department}
 function fixtureId(){if(live)return '';if(state.recordKey!==fixture.selected_record_key)return '';const m=fixture.inquiries[state.department].synthetic_mapping?.[0];return m?.[state.department==='app'?'app_charger_id':'device_charger_id']||''}
 function currentId(){if(live)return '';return state.document?state.document.source?.department_identifier||'':fixtureId()}
 function remember(){if(live)return;try{localStorage.setItem(sessionKey,JSON.stringify({session:state.session,selection:{station:state.station,chargers:state.chargers,recordKey:state.recordKey,source:state.source,department:state.department}}))}catch{state.notice='이 기기에 연결 정보를 보관하지 못했습니다. 현재 탭에서는 계속할 수 있습니다.'}}
 function restore(){try{const saved=JSON.parse(localStorage.getItem(sessionKey)||'null');if(saved?.session){if(typeof saved.session!=='string')throw Error();state.session=saved.session;}const s=saved?.selection;if(s?.station?.station_key&&Array.isArray(s.chargers)&&s.chargers.some(c=>c.record_key===s.recordKey)&&['app','device'].includes(s.department)){Object.assign(state,s);state.question=defaultQuestion(state.department)}}catch{state.error='이전 연결 정보를 읽지 못했습니다. 저장된 기록은 변경하지 않았습니다.'}}
 if(!liveRoute())restore();
 function liveCapabilities(value){return {workspace_sharing:value?.workspace_sharing===true,knowledge_generation:value?.knowledge_generation===true,inquiry_generation:value?.inquiry_generation===true,generation_reason:typeof value?.generation_reason==='string'?value.generation_reason:''}}
 function generationAllowed(mode=state.answerMode){return !live||live.capabilities[mode==='inquiry'?'inquiry_generation':'knowledge_generation']}
 function anyGeneration(){return !live||live.capabilities.knowledge_generation||live.capabilities.inquiry_generation}
 function checkedDataBase(value){const u=new URL(value);if(u.username||u.password||u.search||u.hash||u.pathname.replace(/\/$/,'')!=='/data-platform'||!(u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname))))throw Error('데이터 API 주소를 확인하세요.');return u.origin+'/data-platform'}
 async function visitorRequest(connection,path,{method='GET',body}={}){let response;try{response=await fetch(connection.apiBase+'/visitor/'+path,{method,credentials:'omit',headers:{Authorization:'Bearer '+connection.bearer,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(60000)})}catch{throw Error('입수 원본 연결을 확인하지 못했습니다. 데이터 목록에서 다시 선택해 주세요.')}let result;try{result=await response.json()}catch{throw Error('입수 원본 서버 응답을 확인하지 못했습니다.')}if(!response.ok){const error=Error(response.status===401||response.status===403||response.status===404?'선택한 입수 원본에 접근할 수 없거나 만료되었습니다. 데이터 목록에서 다시 선택해 주세요.':'원본 또는 문서가 바뀌었습니다. 데이터 목록에서 다시 확인해 주세요.');error.versionConflict=response.status===409&&result.error==='현재 버전을 다시 확인하세요.';error.visitorDenied=[401,403,404].includes(response.status)||(response.status===409&&!error.versionConflict);if(error.versionConflict)error.message='다른 수정으로 버전이 바뀌었습니다. 최신 버전을 새로고침한 뒤 보관된 입력을 대조하세요.';throw error}return result}
 function validateContext(value,id){if(value?.context_id!==id||!/^([a-f0-9]{32})$/.test(value.dataset_id)||!['app','device'].includes(value.department)||!value.station||!['name','address','operator'].every(k=>typeof value.station[k]==='string')||!Array.isArray(value.records)||value.records.length<1||value.records.length>3||value.records.some(r=>!Number.isInteger(r.row_number)||r.row_number<1||typeof r.public_charger_id!=='string')||!value.source||!/^[a-f0-9]{64}$/.test(value.source.source_sha256)||typeof value.source.source_bytes!=='number')throw Error('서버가 확인한 선택 문맥 형식을 확인할 수 없습니다.');return value}
 async function openVisitorContext({apiBase:base,visitorBearer,contextId}={}){if(typeof visitorBearer!=='string'||!/^\S{1,4096}$/.test(visitorBearer)||typeof contextId!=='string'||!/^[a-f0-9]{32}$/.test(contextId))throw Error('입수한 자료에서 충전소를 다시 선택해 주세요.');const serial=++handoffSerial,connection={apiBase:checkedDataBase(base),bearer:visitorBearer};const context=validateContext(await visitorRequest(connection,'station-contexts/resolve',{method:'POST',body:{context_id:contextId}}),contextId);if(serial!==handoffSerial)throw new Obsolete();if(!live)demoSnapshot=copy(state);generation++;live={...connection,context,capabilities:liveCapabilities(context.capabilities)};Object.assign(state,{session:null,expired:false,department:context.department,station:{...context.station,station_key:context.fingerprint||context.context_id},chargers:context.records.map(r=>({record_key:context.dataset_id+':row:'+r.row_number,charger_id:r.public_charger_id})),recordKey:context.dataset_id+':row:'+context.records[0].row_number,source:context.source,tab:1,document:null,documents:[],loaded:false,role:'member',question:defaultQuestion(context.department),answerMode:'knowledge',answer:null,draft:null,comparison:null,comparisonError:'',commentDraft:'',humanDraft:null,revisionDraft:null,error:'',notice:'입수 원본의 선택 행과 출처를 서버에서 확인했습니다.',busy:false});location.hash='#scenario-1-live';activate();return {contextId:context.context_id,datasetId:context.dataset_id}}
 function closeLive(){if(!live)return;live=null;generation++;if(demoSnapshot)Object.assign(state,demoSnapshot);demoSnapshot=null}
 async function request(group,action,payload={},department=state.department){const ticket=generation;if(live){if(group!=='kb'||action==='session'||action==='save')throw Error('입수한 자료에서 충전소를 선택해 전용 문서로 이어가세요.');const connection=live;try{const result=await visitorRequest(connection,'kb/'+action,{method:'POST',body:{...payload,department}});if(ticket!==generation||live!==connection||!active)throw new Obsolete();if(['catalog','document'].includes(action))live.capabilities=liveCapabilities(result.capabilities);return result}catch(e){if(ticket!==generation||live!==connection||!active)throw new Obsolete();if(e.visitorDenied)closeLive();throw e}}const response=await fetch(apiBase+'/demo/'+group+'/'+action,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify(group==='kb'&&action!=='session'?{session_id:state.session,org:'alpha',department,sample_pack:'company',...payload}:payload),signal:AbortSignal.timeout(60000)}).catch(()=>{if(ticket!==generation||!active)throw new Obsolete();throw Error('서버에 연결하지 못했습니다. 입력을 유지했습니다. 다시 시도해 주세요.')});const result=await response.json();if(ticket!==generation||!active)throw new Obsolete();if(!response.ok){if(response.status===401&&group==='kb')state.expired=true;throw Error(result.error||'요청을 처리하지 못했습니다. 다시 시도해 주세요.')}return result}
 async function connect(){if(live)return;if(state.expired)throw Error('체험 세션이 만료되었습니다. 새 세션을 열어 주세요.');if(state.session)return;const r=await request('kb','session',{sample_pack:'company'});if(!r.session_id)throw Error('세션 응답을 확인할 수 없습니다.');state.session=r.session_id;remember()}
 async function catalog(){await connect();const r=await request('kb','catalog',{scope:'department'});state.documents=r.documents||[];state.loaded=true;return state.documents}
 async function linkedDocument(id){const d=await request('kb','document',{id});if(!matches(d))throw Error('선택한 원본과 문서의 연결 정보가 다릅니다. 자료에서 다시 선택해 주세요.');return d}
 async function openSelected(){await catalog();const d=state.documents.find(matches);state.document=d?await linkedDocument(d.id):null;await loadComparison();state.answer=null;state.draft=null;state.tab=2;setHash();if(!d)state.notice='선택한 충전기에 연결된 부서 문서가 없습니다. 확인할 내용을 초안으로 남길 수 있습니다.'}
 async function refreshDocument(){if(!state.document)return;const d=await request('kb','document',{id:state.document.id});if(!matches(d))throw Error('선택한 충전기와 문서의 출처가 다릅니다. 대상을 다시 선택해 주세요.');state.document=d;await loadComparison();return d}
 async function loadComparison(){state.comparison=null;state.comparisonError='';const d=state.document;if(d&&d.version>1){const previous=(d.history||[]).filter(v=>v.version<d.version).sort((a,b)=>b.version-a.version)[0];if(previous)try{state.comparison=await request('kb','compare-versions',{id:d.id,from_version:previous.version,to_version:d.version})}catch(e){if(e instanceof Obsolete)throw e;state.comparisonError='현재 문서는 불러왔지만 전후 비교를 불러오지 못했습니다. 최신 버전을 새로고침해 주세요.'}}}

 async function perform(fn){if(state.busy)return;state.busy=true;state.error='';state.notice='';render();try{await fn()}catch(e){if(!(e instanceof Obsolete))state.error=e.message}finally{state.busy=false;render()}}
 function resetContext(){generation++;state.document=null;state.documents=[];state.loaded=false;state.answer=null;state.draft=null;state.comparison=null;state.commentDraft='';state.humanDraft=null;state.revisionDraft=null;state.error='';state.notice='';remember()}
 function setHash(){history.replaceState(null,'','#scenario-'+state.tab+((live||liveRoute())?'-live':''))}
 function refreshCollection(){if(state.tab===5&&(state.session||live)&&!state.busy)return perform(catalog)}
 function go(tab){state.tab=tab;setHash();render();window.scrollTo?.(0,0);return refreshCollection()}
 function button(label,action,extra=''){return `<button data-company-action="${action}" ${state.busy?'disabled':''} ${extra}>${label}</button>`}
 function target(){const c=charger(),id=currentId(),d=state.document;return `<section class="company-target card" aria-label="현재 문의 대상"><div class="eyebrow">${esc(dept(state.department))} 문의 대상</div><h2 class="company-target-id">${esc(id||'내부 ID 확인 필요')}</h2><p>${id?d?`부서 KB에서 가져온 ID · v${esc(d.version)} · ${esc(documentStatus(d))}`:'준비된 연결표의 체험용 ID · 부서 KB 확인 전':'공공 ID에 대응하는 부서 ID가 연결되어 있지 않습니다.'}</p><dl class="company-facts"><dt>${live?'원본':'공공'} 충전기 ID</dt><dd><strong>${esc(live?live.context.records.map(r=>r.public_charger_id).join(', '):c?.charger_id||'선택 필요')}</strong></dd><dt>충전소</dt><dd>${esc(state.station?.name||'선택 필요')}</dd><dt>주소</dt><dd>${esc(state.station?.address||'미제공')}</dd><dt>운영사</dt><dd>${esc(state.station?.operator||'미제공')}</dd></dl>${state.tab===1&&!live?`<div class="company-target-actions"><div class="grid"><label>충전기<select id="company-charger" ${state.busy?'disabled':''}>${state.chargers.map(c=>`<option value="${esc(c.record_key)}" ${c.record_key===state.recordKey?'selected':''}>공공 ID ${esc(c.charger_id)} · ${esc(c.type||'형식 미제공')}</option>`).join('')}</select></label><label>담당 부서<select id="company-department" ${state.busy?'disabled':''}><option value="app" ${state.department==='app'?'selected':''}>앱개발팀</option><option value="device" ${state.department==='device'?'selected':''}>충전기개발팀</option></select></label></div>${button('이 충전기의 부서 KB 열기','open','class="primary"')}</div>`:''}${d?`<p class="company-doc-link">같은 문서로 이어집니다 · <code>${esc(d.id)}</code> · v${esc(d.version)}</p>`:''}</section>`}
 function compactTarget(){const d=state.document,id=currentId();return `<section class="company-context" aria-label="현재 문의 대상"><p><strong>${esc(id||'내부 ID 확인 필요')}</strong> · ${esc(dept(state.department))}</p><p>${esc(state.station?.name||'선택 필요')} · ${live?'원본':'공공'} ID ${esc(live?live.context.records.map(r=>r.public_charger_id).join(', '):charger()?.charger_id||'선택 필요')}</p><p class="muted">${d?`v${esc(d.version)} · ${esc(documentStatus(d))}`:'부서 KB 확인 전'} · 실제 내부 ID 대응은 미검증</p></section>`}
 function contextDetails(){return `<details class="company-context-details"><summary>대상 상세·연결 근거·확인 한계</summary>${target()}${connectionEvidence()}${sourceInfo(state.document)}</details>`}
 function connectionEvidence(){
  const d=state.document,s=live?draftSource():d?.source||draftSource(),same=!!d&&matches(d),mapping=s.mapping_status;
  const mappingLabel=mapping==='synthetic_fixture'?'체험용 연결표':mapping==='user_provided_unverified'?'입력된 ID · 내부 대응 미검증':'내부 대응 미확인';
  return `<section class="card company-connections" aria-label="연결된 근거"><h2>연결된 근거</h2><ol class="company-evidence-chain"><li><span class="eyebrow">01 · ${live?'입수 원본':'공개 원본'}</span><h3>${esc(s.station?.name||'선택 필요')}</h3><p>${live?'원본':'환경부'} 충전기 ID <strong>${esc(s.public_charger_id||'미제공')}</strong></p><details><summary>원본 행 참조</summary><code>${esc(s.record_key||'미제공')}</code></details></li><li><span class="eyebrow">02 · ${esc(dept(state.department))}</span><h3>${esc(s.department_identifier||'ID 확인 필요')}</h3><p>${esc(mappingLabel)}</p></li><li><span class="eyebrow">03 · 근거 KB 문서</span>${d?`<h3>${esc(dept(d.department))} · v${esc(d.version)}</h3><p>${esc(documentStatus(d))}</p><code>${esc(d.id)}</code>`:'<h3>연결된 문서 없음</h3><p>부서 KB를 조회한 뒤 문서와 확인 상태를 연결합니다.</p>'}</li></ol><p><strong>같은 대상으로 연결한 기준</strong><br>${same?(live?'서버가 입수 데이터셋의 선택 행과 출처 지문을 다시 대조했습니다. 문서의 데이터셋·선택 문맥·담당 부서가 이 선택과 일치합니다.':'저장된 출처의 충전소 키·원본 행 키가 현재 선택과 같고, 문서의 담당 부서가 선택 부서와 일치합니다.'):d?'문서 출처와 현재 선택이 일치하지 않습니다. 대상을 다시 확인해야 합니다.':'선택한 원본 행과 부서로 문서를 찾습니다. 공공 ID만으로 연결하지 않습니다.'} ${d?`문서 본문은 현재 ${esc(documentStatus(d))} 상태입니다.`:''}</p><p><strong>아직 확인하지 않은 것</strong><br>공공 원본과 실제 내부 시스템 ID의 대응 관계입니다. 문서의 확인 상태가 실제 내부 매핑을 검증했다는 뜻은 아닙니다.</p><p class="muted">${state.tab===5?'모음에서는 선택한 부서와 승인된 전사 범위를 조회합니다. 문서를 고르면 그 문서만 근거로 사용합니다.':live&&!anyGeneration()?'AI 생성 없이 선택한 문서의 확인된 원문만 조회합니다.':'AI 조회 범위는 선택한 이 문서 하나입니다.'} 다른 부서·조직의 문서를 자동으로 합치거나 연결 근거로 사용하지 않습니다.</p></section>`
 }
 function sourceInfo(d){const s=live?draftSource():d?.source||draftSource(),p=s.public_source||state.source||{};const sourceTime=p.collection_finished_at||p.collected_at||p.fetched_at||(p.dataset_created_at?new Date(p.dataset_created_at*1000).toLocaleString('ko-KR'):'미제공');return `<details class="company-source"><summary>출처·데이터 안내</summary><p>${live?'입수':'공개'} 원문은 충전소·주소·운영사·원본 ID의 출처입니다. 입수 시점의 보관본이며 현재 상태와 다를 수 있습니다.</p><dl class="company-facts"><dt>원본 행</dt><dd>${esc(s.record_key||state.recordKey)}</dd><dt>수집 시각</dt><dd>${esc(sourceTime)}</dd><dt>자료 범위</dt><dd>${esc(p.dataset_scope||p.snapshot_kind||(live?'이번 방문자가 입수한 원본':'공개 원문 보존본'))}</dd><dt>원문</dt><dd>${esc(p.source_url||(live?'방문자가 올린 파일':'출처 URL 미제공'))}</dd>${live?`<dt>데이터셋</dt><dd>${esc(live.context.dataset_id)}</dd><dt>원본 SHA-256</dt><dd>${esc(p.source_sha256)}</dd><dt>원본 크기</dt><dd>${esc(p.source_bytes)}바이트</dd>`:''}</dl></details>`}
 function draftSource(){if(live){const c=live.context;return {station:c.station,record_key:c.dataset_id+' / RAW 행 '+c.records.map(r=>r.row_number).join(', '),public_charger_id:c.records.map(r=>r.public_charger_id).join(', '),public_source:c.source,department_identifier:'',mapping_status:'unconfirmed'}}return {kind:'company_charger_knowledge',station:copy(state.station),record_key:state.recordKey,public_charger_id:charger()?.charger_id||'',department:state.department,public_source:copy(state.source),mapping_status:fixtureId()?'synthetic_fixture':'unconfirmed',department_identifier:fixtureId(),synthetic:true}}
 function initialContent(){const id=fixtureId(),c=charger();return `${dept(state.department)} 문의 기준\n\n대상: ${state.station.name} / 공공 충전기 ID ${c?.charger_id||''}\n주소: ${state.station.address.trim()}\n운영사: ${state.station.operator}\n\n${id?`부서 문의 ID: ${id}\n공개 ID·주소·운영사로 같은 대상인지 대조합니다.`:'부서 내부 ID: 확인 필요\n공공 ID만으로 내부 장비를 특정하지 않습니다. 담당 부서에 연결 근거와 ID를 확인합니다.'}\n\n전달할 정보\n${state.department==='app'?'앱 오류 화면, 발생 시각, 오류 코드':'장비 증상, 발생 시각, 장비 로그'}\n공공 충전기 ID, 충전소 주소, 운영사, 원본 행 참조\n\n적용 조건\n${id?'체험용 연결표의 문의 절차입니다. 실제 대응 관계는 별도 확인이 필요합니다.':'내부 대응 관계와 적용 기간을 확인한 뒤 기준을 확정합니다.'}`}
 function documentBody(d){return `<section class="card company-document"><div class="row"><h2>${esc(d.title)}</h2><span class="badge">v${esc(d.version)} · ${esc(documentStatus(d))}</span></div><dl class="company-facts"><dt>담당 부서</dt><dd>${esc(dept(d.department))}</dd><dt>적용일</dt><dd>${esc(d.valid_from||'미등록')} ~ ${esc(d.valid_to||'미등록')}</dd><dt>문서 ID</dt><dd><code>${esc(d.id)}</code></dd></dl>${reviewSummary(d)}<pre class="company-body">${esc(d.content)}</pre>${sourceInfo(d)}${comments(d)}${button('최신 버전 새로고침','refresh')}</section>`}
 function comments(d){return `<section class="company-comments" aria-label="문서 댓글"><h3>댓글과 처리 상태</h3>${(d.comments||[]).map(c=>`<article class="company-comment"><div class="row"><strong>${c.author_role==='reviewer'?'담당자':'구성원'} · v${esc(c.version)}</strong><span class="badge">${c.resolved_version?'v'+esc(c.resolved_version)+'에 반영':c.pending_version?'v'+esc(c.pending_version)+'에 반영 예정 · 확인 대기':'확인 대기'}</span></div><p>${esc(c.body)}</p></article>`).join('')||'<p>아직 댓글이 없습니다.</p>'}</section>`}
 function historyMarkup(d){const pair=state.comparison,rows=pair?[pair.after,pair.before]:[d];return `<section class="card company-history"><h2>정정 전후와 버전 이력</h2>${state.comparisonError?`<p role="alert">${esc(state.comparisonError)}</p>`:''}${rows.map((v,i)=>`<article><h3>${pair?(i===0?'정정 후':'정정 전'):'현재 기준'} · v${esc(v.version)} · ${esc(documentStatus(v))}</h3><p><strong>변경 이유</strong> ${esc(v.reason||'최초 등록')}</p><pre class="company-body">${esc(v.content)}</pre></article>`).join('')}<p>보관된 버전: ${(d.history||[]).map(v=>'v'+esc(v.version)).join(' → ')||'v'+d.version}</p>${(d.history||[]).filter(v=>v.version<d.version).map(v=>`<button data-compare="${v.version}" ${state.busy?'disabled':''}>v${v.version}와 현재 버전 비교</button>`).join('')}</section>`}

 function emptyDocument(){if(live)return `<section class="card"><h2>선택 원본에 연결된 방문자 KB</h2><p>이 방문자 세션과 선택 문맥 안에서 문서를 이어갑니다. 다른 조직의 기록과 섞이지 않습니다.</p>${button('선택 원본의 KB 확인','open','class="primary"')}${state.loaded?button('선택 원문으로 KB 초안 만들기','live-draft'):''}</section>`;if(!state.station||!charger())return `<section class="card"><h2>충전기를 먼저 선택하세요</h2>${button('문의 대상 찾기로 이동','step1')}</section>`;return `<section class="card"><h2>선택한 충전기의 부서 문서</h2><p>${state.loaded?'연결된 문서가 없습니다. 확인할 내용을 먼저 초안으로 남기세요.':'같은 충전기와 부서에 연결된 서버 KB를 확인하세요.'}</p>${button('선택한 충전기의 부서 KB 열기','open','class="primary"')}${state.loaded?button('문서 초안 작성하기','compose'):''}</section>`}
 function searchView(){if(live)return `<section class="card"><h2>입수한 원본에서 선택한 충전소</h2><p>데이터셋 <code>${esc(live.context.dataset_id)}</code> · RAW 행 ${live.context.records.map(r=>r.row_number).join(', ')}</p><p>내부 앱·장비 ID는 아직 확인되지 않았습니다. 원본을 근거로 업무 확인 초안을 남길 수 있습니다.</p>${button('선택 원본의 KB 확인','open','class="primary"')}<a class="button" href="#data">입수한 자료로 돌아가기</a>${sourceInfo()}</section>`;return `<form id="company-search" class="card"><h2>다른 충전소 찾기</h2><div class="grid"><label>지역·주소·건물명<input name="q" value="${esc(state.q)}" required></label><label>공공 충전기 ID (선택)<input name="charger" value="${esc(state.chargerId)}"></label></div><button class="primary" ${state.busy?'disabled':''}>충전소 검색</button><p class="muted">공개 원문에서 대상을 찾습니다. 검색 범위와 수집 시각은 출처에서 확인할 수 있습니다.</p></form><section class="card"><h2>충전소 후보 · ${state.total}개</h2>${state.stations.map((s,i)=>`<button class="station-option" data-station="${i}" ${state.busy?'disabled':''}><strong>${esc(s.name)}</strong><span>${esc(s.address)}</span><small>${esc(s.operator)}</small></button>`).join('')||'<p>검색 결과가 없습니다. 주소나 건물명을 바꿔 주세요.</p>'}${state.stations.length<state.total?button('후보 더 보기','more'):''}</section>${state.station?`<section class="card"><h2>문의할 때 전달할 항목</h2><ul><li><strong>대상 확인:</strong> 부서 ID, 공공 ID, 충전소 주소, 운영사</li><li><strong>문제 설명:</strong> ${state.department==='app'?'앱 오류 화면·발생 시각·오류 코드':'장비 증상·발생 시각·장비 로그'}</li><li><strong>확인 요청:</strong> 같은 대상인지, 사용할 기준과 적용 기간</li></ul>${sourceInfo(state.document)}</section>`:''}`}
 function compose(){const draft=state.draft||{content:initialContent(),valid_from:'2026-09-01',valid_to:'2026-12-31'};return `<form id="company-save" class="card"><h2>확인할 내용을 부서 문서로 남기기</h2><p>문의 내용은 초안으로 저장됩니다. 담당자 확인을 마쳐야 다음 사람이 근거로 조회할 수 있습니다.</p><label>문서 본문<textarea name="content" rows="12" required>${esc(draft.content)}</textarea></label><div class="grid"><label>적용 시작<input name="valid_from" type="date" value="${esc(draft.valid_from)}" required></label><label>적용 종료<input name="valid_to" type="date" value="${esc(draft.valid_to)}" required></label></div><button class="primary" ${state.busy?'disabled':''}>부서 KB에 초안 저장</button></form>`}
 function captureView(){return state.document?`<div class="actions">${button('검토 기록 작성·완료하기','step3','class="primary"')}</div>`+documentBody(state.document)+`<div class="actions">${button('댓글·정정으로 이어가기','step3','class="primary"')}</div>`:emptyDocument()+(state.draft?compose():'')}
 function documentStatus(d,evidence=false){if(d?.state!=='confirmed')return status(d?.state);const r=humanReview(d);return r.current?'이 버전 검토 완료':r.malformed?'서버 확인 상태 · 검토 기록 확인 필요':r.record?'서버 확인 상태 · 현재 버전 검토 기록 없음':evidence?'서버 확인 상태 · 반환 근거에서 검토 기록 확인 불가':'서버 확인 상태 · 검토 기록 미등록'}
 const reviewStart='[사람이 남긴 검토 기록]',reviewEnd='[검토 기록 끝]';
 const reviewOutcomes={apply:'업무에 적용 가능',conditional:'일부 조건에서만 적용',unknown:'확인되지 않아 사용 보류'};
 function validReviewRecord(r){return !!(reviewOutcomes[r.outcome]&&['facts','conditions','unknowns','next'].every(key=>typeof r[key]==='string'&&r[key].trim()&&r[key].length<=1000&&!r[key].includes(reviewStart)&&!r[key].includes(reviewEnd))&&!(r.outcome==='unknown'&&r.unknowns==='미확인 사항 없음')&&!((r.outcome==='unknown'||r.unknowns!=='미확인 사항 없음')&&r.next==='추가 확인 행동 없음'))}
 function humanReview(d){
  const content=d?.content||'',start=content.indexOf(reviewStart),end=content.indexOf(reviewEnd,start);
  if(start<0)return {record:null,base:content,current:false};
  if(end<0||content.indexOf(reviewStart,start+reviewStart.length)>=0)return {record:null,base:content,current:false,malformed:true};
  const block=content.slice(start,end+reviewEnd.length),match=block.match(/^\[사람이 남긴 검토 기록\]\n문서 버전: (\d+)\n검토 결론: (.+)\n확인한 내용과 근거:\n((?:  .*\n)+)적용 조건·재확인 조건:\n((?:  .*\n)+)미확인 사항:\n((?:  .*\n)+)다음 확인 행동:\n((?:  .*\n)+)\[검토 기록 끝\]$/);
  if(!match)return {record:null,base:content,current:false,malformed:true};
  const unpack=x=>x.trimEnd().split('\n').map(line=>line.slice(2)).join('\n');
  const record={version:Number(match[1]),outcome:Object.keys(reviewOutcomes).find(key=>reviewOutcomes[key]===match[2]),facts:unpack(match[3]),conditions:unpack(match[4]),unknowns:unpack(match[5]),next:unpack(match[6])};
  const valid=validReviewRecord(record);
  const cut=start>=2&&content.slice(start-2,start)==='\n\n'?start-2:start;
  return {record,base:content.slice(0,cut)+content.slice(end+reviewEnd.length),current:!!valid&&record.version===d.version,malformed:!valid};
 }
 function reviewContent(d,values){
  const prior=humanReview(d);if(prior.malformed)throw Error('기존 검토 기록 형식이 달라 자동 교체하지 않았습니다. 본문 정정에서 기록을 확인하세요.');
  const record={outcome:values.outcome,facts:String(values.facts||'').trim(),conditions:String(values.conditions||'').trim(),unknowns:values.no_unknown?'미확인 사항 없음':String(values.unknowns||'').trim(),next:String(values.next||'').trim()};
  if(!reviewOutcomes[record.outcome]||!record.facts||!record.conditions||!record.unknowns)throw Error('검토 결론, 확인 근거, 적용 조건, 미확인 사항을 모두 남겨 주세요.');
  if(record.outcome==='unknown'&&values.no_unknown)throw Error('사용 보류의 이유가 되는 미확인 사항을 적어 주세요.');
  if((record.outcome==='unknown'||!values.no_unknown)&&!record.next)throw Error('사용 보류 또는 미확인 사항이 있으면 다음 확인 행동을 남겨 주세요.');
  if(!record.next)record.next='추가 확인 행동 없음';
  for(const value of Object.values(record)){if(value.includes(reviewStart)||value.includes(reviewEnd))throw Error('검토 기록 구분 문구는 입력 내용에 넣을 수 없습니다.');if(value.length>1000)throw Error('각 검토 항목은 1,000자 이하로 입력하세요.');}
  if(!validReviewRecord(record))throw Error('검토 결론과 미확인 사항, 다음 확인 행동이 서로 모순되지 않도록 작성하세요.');
  const indent=value=>value.split('\n').map(line=>'  '+line).join('\n');
  const content=prior.base+'\n\n'+reviewStart+'\n문서 버전: '+(d.version+1)+'\n검토 결론: '+reviewOutcomes[record.outcome]+'\n확인한 내용과 근거:\n'+indent(record.facts)+'\n적용 조건·재확인 조건:\n'+indent(record.conditions)+'\n미확인 사항:\n'+indent(record.unknowns)+'\n다음 확인 행동:\n'+indent(record.next)+'\n'+reviewEnd;
  if(new TextEncoder().encode(content).length>7000)throw Error('본문과 검토 기록을 합쳐 UTF-8 7,000바이트 이하로 정리해 주세요. 입력 내용은 유지했습니다.');return content;
 }
 function reviewSummary(d,evidence=false){const r=humanReview(d);return `<div class="company-review-summary"><strong>${r.current?'이 버전의 검토 기록 있음':r.malformed?'검토 기록 확인 필요':r.record?'이전 버전의 검토 기록 · 다시 검토 필요':evidence?'반환된 근거에서 검토 기록 확인 불가':'검토 기록 미등록'}</strong>${r.current?`<p>사람이 남긴 결론: ${esc(reviewOutcomes[r.record.outcome])}</p><p>적용 조건: ${esc(r.record.conditions)}</p><p>미확인 사항: ${esc(r.record.unknowns)}</p>`:'<p>서버의 확인 상태만으로 업무 판단이나 내부 ID 대응이 검증된 것은 아닙니다.</p>'}${!evidence&&(!d.valid_from||!d.valid_to)?'<p>기간 미기재 — 무기한 적용을 뜻하지 않습니다. 적용·재확인 조건을 확인하세요.</p>':''}</div>`}
 function humanReviewPane(d){if(state.role!=='reviewer')return `<section class="card company-human-review"><h2>사람의 검토 기록</h2>${button('검토자 역할로 작성하기','reviewer','class="primary"')}${reviewSummary(d)}<p class="muted">현재 작업공간의 검토자 역할 체험입니다. 실제 회사의 권한이나 승인을 뜻하지 않습니다.</p></section>`;const r=humanReview(d),v=state.humanDraft?.id===d.id?state.humanDraft:r.record||{};return `<section class="card company-human-review"><h2>사람의 검토 기록</h2>${reviewSummary(d)}${state.humanDraft&&state.humanDraft.version!==d.version?button('최신 본문을 대조하고 입력 이어쓰기','rebase-human-review'):''}${r.current&&d.state!=='confirmed'?button('이 버전의 검토 완료','complete-human-review',`class="primary" ${state.humanDraft?'disabled':''}`):''}${d.state==='confirmed'&&r.current?'<p>이 버전의 검토를 완료했습니다. 전사 공유 승인은 별도입니다.</p>':''}<details ${!r.current||state.humanDraft?'open':''}><summary>${r.current?'검토 내용 수정 · 새 버전으로 저장':'검토 내용 작성하기'}</summary><form id="company-human-review"><p>확인한 근거와 아직 모르는 점을 직접 기록하세요. 내부 ID가 없어도 사용 보류와 다음 확인 행동을 남길 수 있습니다.</p><label>검토 결론<select name="outcome" required><option value="">결론을 선택하세요</option>${Object.entries(reviewOutcomes).map(([key,label])=>`<option value="${key}" ${v.outcome===key?'selected':''}>${label}</option>`).join('')}</select></label><label>확인한 내용과 근거<textarea name="facts" rows="3" required maxlength="1000" placeholder="실제로 대조한 원문 항목이나 담당자 회신을 적으세요.">${esc(v.facts||'')}</textarea></label><label>적용 조건·재확인 조건<textarea name="conditions" rows="3" required maxlength="1000" placeholder="어떤 대상과 상황에 적용할지, 언제 다시 확인할지 적으세요.">${esc(v.conditions||'')}</textarea></label><label class="check"><input name="no_unknown" type="checkbox" ${v.no_unknown||v.unknowns==='미확인 사항 없음'?'checked':''}>미확인 사항 없음</label><label>아직 확인하지 못한 사항<textarea name="unknowns" rows="2" maxlength="1000">${esc(v.unknowns==='미확인 사항 없음'?'':v.unknowns||'')}</textarea></label><label>다음 확인 행동<textarea name="next" rows="2" maxlength="1000" placeholder="미확인 사항 또는 사용 보류가 있으면 반드시 적으세요.">${esc(v.next||'')}</textarea></label>${(d.comments||[]).filter(c=>!c.resolved_version).map(c=>`<label class="check"><input name="resolve" type="checkbox" value="${esc(c.id)}" ${(v.resolve_comment_ids||[]).includes(c.id)?'checked':''}>이 검토에 반영: ${esc(c.body)}</label>`).join('')}<button class="primary" ${state.busy?'disabled':''}>검토 내용을 새 초안으로 저장</button><p>저장만으로 검토 완료나 전사 공유가 되지 않습니다.</p></form></details><details><summary>검토 상태의 의미</summary><p>원문 대조는 서버가 보관한 출처의 일치 확인입니다. 검토 완료는 사람이 이 버전의 판단과 한계를 기록했다는 뜻이며 실제 회사의 승인이나 내용의 정확성을 보증하지 않습니다. 이 양식은 화면의 입력 절차이며 서버 권한·검증 규칙을 추가하지 않습니다.</p></details></section>`}
 async function saveHumanReview(values){if(state.role!=='reviewer')throw Error('검토자 역할로 전환하세요.');const d=state.document;state.humanDraft={...values,id:d.id,version:values.version??d.version};if(state.humanDraft.version!==d.version)throw Error('문서 버전이 바뀌었습니다. 보관된 입력을 현재 본문과 대조한 뒤 다시 작성하세요.');const content=reviewContent(d,values);await request('kb','revise',{id:d.id,version:d.version,content,reason:'사람 검토 기록: '+reviewOutcomes[values.outcome],resolve_comment_ids:values.resolve_comment_ids||[]});await refreshDocument();state.humanDraft=null;state.answer=null;state.notice='검토 내용을 같은 문서의 새 초안으로 저장했습니다. 내용을 대조한 뒤 별도로 검토 완료하세요.'}
 async function completeHumanReview(){if(state.role!=='reviewer')throw Error('검토자 역할로 전환하세요.');if(state.humanDraft)throw Error('입력 중인 검토 내용을 먼저 새 초안으로 저장하세요.');const d=state.document,r=humanReview(d);if(!r.current)throw Error('현재 버전의 검토 기록을 먼저 저장하세요.');await request('kb','review',{id:d.id,version:d.version,state:'confirmed',reason:'이 버전 검토 완료: '+reviewOutcomes[r.record.outcome]});await refreshDocument();state.answer=null;state.notice='이 버전의 검토를 완료했습니다. 기록된 적용 조건과 미확인 사항을 함께 사용하세요. 전사 공유는 별도 승인입니다.'}

 function correctView(){const d=state.document;if(!d)return emptyDocument();return humanReviewPane(d)+documentBody(d)+`<form id="company-comment" class="card"><h2>빠진 조건이나 오류 알리기</h2><label>문서에 남길 댓글<textarea name="body" required maxlength="1000" rows="3">${esc(state.commentDraft)}</textarea></label><button ${state.busy?'disabled':''}>댓글 남기기</button></form><section class="card"><h2>담당자가 기준 확인·정정</h2><label>현재 역할<select id="company-role" ${state.busy?'disabled':''}><option value="member" ${state.role==='member'?'selected':''}>문의하는 구성원</option><option value="reviewer" ${state.role==='reviewer'?'selected':''}>담당자 역할로 검토</option></select></label>${state.role==='reviewer'?`<form id="company-revise"><label>정정할 본문<textarea name="content" rows="12" required>${esc(state.revisionDraft?.content??d.content)}</textarea></label>${live?'':`<label>상단에 표시할 부서 ID<input name="department_identifier" value="${esc(state.revisionDraft?.department_identifier??d.source?.department_identifier??'')}" maxlength="100" placeholder="연결 근거가 없으면 비워 두세요"></label><p class="muted">본문의 ID를 정정했다면 이 항목도 함께 바꾸세요. 미연결 대상에는 ID를 추정해 넣지 않습니다.</p>`}<label>변경 이유<input name="reason" value="${esc(state.revisionDraft?.reason||'')}" required maxlength="1000"></label>${(d.comments||[]).filter(c=>!c.resolved_version).map(c=>`<label class="check"><input type="checkbox" name="resolve" value="${esc(c.id)}">이 댓글 반영: ${esc(c.body)}</label>`).join('')}<p>정정본은 새 버전의 초안입니다. 확인 완료 후 다음 사람의 조회에 반영됩니다.</p><button class="primary" ${state.busy?'disabled':''}>정정본을 새 버전으로 저장</button></form>`:'<p>댓글을 남긴 뒤 담당자 역할로 전환하면 정정 과정을 이어볼 수 있습니다.</p>'}</section>${historyMarkup(d)}${button('다음 사람이 최신 기준 조회','step4')}`}
 function answerMarkup(){const r=state.answer;if(!r)return '';return `<section class="card company-answer"><h2>${r.ai_generated?'답변':'조회한 원문 근거'}</h2><p><strong>질문</strong> ${esc(state.answerQuestion)}</p>${r.ai_generated?`<span class="badge">${String(r.ai?.status||'').includes('모의')?'모의 응답 · 실제 모델 호출 없음':'AI 생성 · 원문 대조 필요'}</span><pre class="company-body">${esc(r.answer)}</pre>`:`<p>${esc(r.error_code||r.ai?.error_code?'답변 생성을 완료하지 못했습니다. 아래 원문 근거를 확인해 주세요.':'AI를 생성하지 않고 선택한 문서의 원문을 확인했습니다.')}</p>`}${(r.evidence||[]).map(e=>`<article class="company-evidence"><h3>${esc(e.title||e.name||'문서 근거')} · v${esc(e.version)}</h3><p>${esc(dept(e.department||state.department))} · 문서 ${esc(e.id||e.document_id||state.document?.id)}</p>${reviewSummary({...e,content:e.text||e.content||e.snippet||''},true)}<pre class="company-body">${esc(e.text||e.content||e.snippet||'')}</pre></article>`).join('')||'<p>현재 적용일에 사용할 확인된 근거가 없습니다.</p>'}</section>`}
 function reuseView(){const d=state.document;if(!d)return emptyDocument();return documentBody(d)+`<form id="company-ask" class="card"><h2>같은 최신 문서에 질문하기</h2><p>조회 대상: <strong>${esc(d.title)} · v${esc(d.version)}</strong></p><p class="muted">이 문서의 최신 확인 본문만 근거로 사용합니다. 위 연결 정보를 별도로 검증하거나 다른 부서 문서를 함께 검토하는 기능은 아닙니다.</p><label>질문<textarea name="question" required maxlength="1000" rows="3">${esc(state.question)}</textarea></label><div class="grid"><label>업무 적용일<input type="date" name="as_of" value="${esc(state.asOf)}" required></label>${live&&!anyGeneration()?'':`<label>요청할 내용<select name="answer_mode"><option value="knowledge" ${state.answerMode==='knowledge'?'selected':''}>기준 설명</option><option value="inquiry" ${state.answerMode==='inquiry'?'selected':''} ${!generationAllowed('inquiry')?'disabled':''}>담당자에게 보낼 문의 초안</option></select></label>`}</div><div class="actions"><button data-generate="false" ${state.busy||d.state!=='confirmed'?'disabled':''}>근거만 확인</button>${live&&!anyGeneration()?'':`<button class="primary" data-generate="true" ${state.busy||d.state!=='confirmed'||!generationAllowed()||window.KNOWHOW_CONFIG?.aiRequestsPaused!==false?'disabled':''}>AI에 질문하기</button>`}</div>${d.state!=='confirmed'?'<p>담당자가 현재 버전의 확인을 완료해야 조회할 수 있습니다.</p>':''}<p class="muted">${live?esc(live.capabilities.generation_reason||(!anyGeneration()?'현재 방문자 연결은 확인된 원문 근거만 조회할 수 있습니다. AI 생성은 아직 지원하지 않습니다.':'기본은 원문 조회이며, 별도 생성 버튼을 눌러 AI 초안을 요청할 수 있습니다.')):'기본은 원문 조회입니다. AI 요청은 별도 생성 버튼을 누를 때만 실행됩니다. 문서 이동·댓글·원문 조회는 AI를 호출하지 않습니다.'}</p></form>${answerMarkup()}${button('부서 KB 목록에서 확인','step5')}`}
 function legacy(){try{const rows=JSON.parse(localStorage.getItem(legacyKey)||'[]');if(!Array.isArray(rows))throw Error();return rows.length?`<details class="card"><summary>이전에 이 기기에 저장한 기록 ${rows.length}개</summary><p>서버 문서와 별도로 보관된 이전 기록입니다.</p>${rows.map(d=>`<article><h3>${esc(d.name||d.id)}</h3>${(d.versions||[]).map(v=>`<h4>v${esc(v.version)}</h4><pre class="company-body">${esc(v.content)}</pre>`).join('')}${(d.comments||[]).map(c=>`<p>댓글: ${esc(c.body)}</p>`).join('')}</article>`).join('')}</details>`:''}catch{return '<p>이전 저장 기록을 읽지 못했습니다. 원본은 변경하지 않았습니다.</p>'}}
 function collectionView(){if(window.KnowHowOrganizationUI)return `<div id="company-shared-library"></div>${live?'<a class="button" href="#data">입수한 자료로 돌아가기</a>':legacy()+`<details id="company-materials" class="card"><summary>별도 자료 추가 · TXT/MD</summary><p>추가 자료를 이 기기에서 읽습니다. 선택한 서버 문서에 자동으로 합쳐지지 않습니다.</p><div id="company-source-records"></div></details>`}`;if(live)return `<section class="card"><h2>이번 선택의 방문자 KB</h2><p>${esc(dept(state.department))} · 데이터셋 ${esc(live.context.dataset_id)}</p>${button('연결된 문서 새로고침','catalog')}${state.documents.filter(matches).map(d=>`<article class="company-library-row"><h3>${esc(d.title)}</h3><p>v${esc(d.version)} · ${esc(documentStatus(d))}</p><code>${esc(d.id)}</code><button data-document="${esc(d.id)}" ${state.busy?'disabled':''}>이 문서 열기</button></article>`).join('')||'<p>이 선택 문맥에 연결된 문서가 아직 없습니다.</p>'}<a class="button" href="#data">입수한 자료로 돌아가기</a></section>`;return `<section class="card"><h2>${esc(dept(state.department))} KB</h2><label>부서<select id="company-department" ${state.busy?'disabled':''}><option value="app" ${state.department==='app'?'selected':''}>앱개발팀</option><option value="device" ${state.department==='device'?'selected':''}>충전기개발팀</option></select></label><p>현재 격리 세션의 부서 문서입니다. 같은 문서를 열어 댓글·정정·조회를 이어갑니다.</p>${button('부서 문서 목록 새로고침','catalog','class="primary"')}${state.documents.filter(d=>d.source?.kind==='company_charger_knowledge').map(d=>`<article class="company-library-row"><h3>${esc(d.title)}</h3><p>${esc(d.source.station?.name)} · 공공 ID ${esc(d.source.public_charger_id)} · v${esc(d.version)} · ${esc(documentStatus(d))}</p><p><code>${esc(d.id)}</code></p><button data-document="${esc(d.id)}" ${state.busy?'disabled':''}>이 문서 열기</button></article>`).join('')||'<p>목록을 열어 연결된 문서를 확인하세요.</p>'}</section>${legacy()}<details id="company-materials" class="card"><summary>별도 자료 추가 · TXT/MD</summary><p>추가 자료를 이 기기에서 읽습니다. 선택한 서버 문서에 자동으로 합쳐지지 않습니다.</p><div id="company-source-records"></div></details>`}
 function render(){if(!active)return;if(liveRoute()&&!live){$('#page').innerHTML='<section class="card"><h1>입수한 자료에서 다시 선택해 주세요</h1><p>페이지를 다시 열었거나 선택 문맥이 만료되어 연결 정보를 사용할 수 없습니다. 최근 입수 목록으로 돌아가 충전소를 다시 선택하세요.</p><a class="button primary" href="#data">입수한 자료로 돌아가기</a></section>';return}sharingView?.();sharingView=null;sourceView?.destroy();sourceView=null;const views=[searchView,captureView,correctView,reuseView,collectionView];$('#page').innerHTML=`<div class="company-workflow"><div class="eyebrow">KNOWLEDGE · 0${state.tab}</div><h1>${tabs[state.tab-1]}</h1>${state.station?(state.tab===1?target()+connectionEvidence():compactTarget()):''}${state.error?`<p class="notice" role="alert">${esc(state.error)}</p>`:''}${state.expired?button('새 격리 세션 열기','new-session'):''}<p role="status">${esc(state.notice)}</p>${views[state.tab-1]()}${state.station&&state.tab>1?contextDetails():''}</div>`;document.querySelectorAll('[data-scenario]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.scenario)===state.tab);b.setAttribute('aria-current',Number(b.dataset.scenario)===state.tab?'page':'false')});bind()}
 async function search(append=false){const r=await request('workflow','search',{q:state.q,charger_id:state.chargerId,limit:20,offset:append?state.stations.length:0});state.stations=append?[...state.stations,...r.stations]:r.stations;state.total=r.total;state.source=r.source;if(!append){state.station=null;state.chargers=[];state.recordKey='';resetContext()}}
 async function selectStation(i){const s=state.stations[i],r=await request('workflow','chargers',{station_key:s.station_key,limit:50,offset:0});state.station=r.station;state.chargers=r.chargers;state.recordKey=r.chargers[0]?.record_key||'';state.source=r.source;resetContext()}
 async function saveDraft(values){await catalog();const existing=state.documents.find(matches);if(existing){state.document=await linkedDocument(existing.id);throw Error('같은 대상의 문서가 이미 있습니다. 기존 문서를 열었습니다. 정정 기능을 이용해 주세요.')}if(values.valid_from>values.valid_to)throw Error('적용 기간 순서를 확인하세요.');const r=await request('kb','save',{title:state.station.name+' · 공공 ID '+charger().charger_id+' · '+dept(state.department)+' 문의 기준',...values,source:draftSource(),identifiers:fixtureId()?[fixtureId()]:[],visibility:'department'});state.document=await linkedDocument(r.id);state.draft=null;state.notice='부서 KB에 초안으로 저장했습니다. 같은 문서에서 댓글과 담당자 확인을 이어갑니다.'}
 async function ask(values){state.question=values.question;state.asOf=values.as_of;state.answerMode=values.answer_mode;await refreshDocument();if(state.document.state!=='confirmed')throw Error('최신 버전의 담당자 확인이 필요합니다.');if(values.generate&&!generationAllowed(values.answer_mode))throw Error('현재 연결에서는 이 방식의 AI 생성을 지원하지 않습니다. 원문 근거를 확인해 주세요.');if(values.generate&&window.KNOWHOW_CONFIG?.aiRequestsPaused!==false)throw Error('현재 AI 생성 요청을 사용할 수 없습니다.');state.answer=null;const r=await request('kb','chat',{...values,document_id:state.document.id,include_company:false});state.answer=r;state.answerQuestion=values.question}
 async function postComment(body){state.commentDraft=body;const r=await request('kb','comment',{id:state.document.id,version:state.document.version,body,author_role:state.role});state.document.comments=r.comments||[...(state.document.comments||[]),r.comment];state.commentDraft='';state.notice='댓글을 문서 아래에 남겼습니다. 담당자 확인 대기 중입니다.'}
 async function reviseDocument(values){if(state.role!=='reviewer')throw Error('담당자 역할로 전환하세요.');state.revisionDraft=values;const d=state.document,{department_identifier,...fields}=values;const source={...d.source,department_identifier,mapping_status:department_identifier===d.source?.department_identifier?d.source.mapping_status:department_identifier?'user_provided_unverified':'unconfirmed'};await request('kb','revise',{id:d.id,version:d.version,...fields,...(!live?{source,identifiers:department_identifier?[department_identifier]:[]}:{} )});await refreshDocument();state.revisionDraft=null;state.answer=null;state.notice='정정본을 새 초안 버전으로 저장했습니다. 아래에서 전후 본문을 확인하고 현재 버전의 확인을 완료하세요.'}

 async function reviewDocument(){if(state.role!=='reviewer')throw Error('담당자 역할로 전환하세요.');await request('kb','review',{id:state.document.id,version:state.document.version,state:'confirmed',reason:state.document.reason||'담당자 역할로 본문과 적용 조건 확인'});await refreshDocument();state.answer=null;state.notice='현재 버전의 확인을 완료했습니다. 다음 조회부터 이 버전을 사용합니다.'}
 async function createLiveDraft(){if(!live)throw Error('입수한 자료에서 다시 선택하세요.');await catalog();const existing=state.documents.find(matches);if(existing){state.document=await linkedDocument(existing.id)}else{const r=await request('kb','data-draft',{context_id:live.context.context_id,dataset_id:live.context.dataset_id});state.document=await linkedDocument(r.id)}state.tab=2;setHash();state.notice='서버가 선택 원본을 연결한 초안입니다. 확인은 별도로 진행해 주세요.'}

 function sharedAdapter(){const owner=state.department,session=state.session,connection=live,ticket=generation;return {
  context:{session:session||'current-company-workspace',org:connection?'개인 방문자 작업공간':'alpha',department:owner,departments:connection?['app','device','data']:['app','device'],documents:state.documents,documentId:state.document?.id,loaded:state.loaded},
  notice:connection?'같은 개인 방문자 작업공간의 부서·전사 공유 체험입니다. 실제 회사의 승인이나 다른 방문자와의 공유가 아닙니다.':'현재 충전 업무의 같은 격리 세션입니다. 가상 부서의 확인·전사 공유를 체험하며 실제 회사 자료나 권한과 연결되지 않습니다.',
  documentStatus,evidenceStatus:e=>documentStatus({...e,content:e.text||e.content||e.snippet||''},true),reviewSummary,reviewEvidence:e=>reviewSummary({...e,content:e.text||e.content||e.snippet||''},true),canShareDocument:d=>humanReview(d).current&&d.state==='confirmed',canReviewDocument:d=>d.id===state.document?.id,openReview:d=>perform(async()=>{if(d.id!==state.document?.id)throw Error('먼저 원문 대상에서 이 문서를 선택하세요.');await refreshDocument();state.role='reviewer';go(3)}),
  canShare:()=>!connection||live?.capabilities.workspace_sharing===true,canGenerate:mode=>generationAllowed(mode),generationReason:()=>live?.capabilities.generation_reason||'현재 AI 생성을 사용할 수 없습니다. 원문 근거는 조회할 수 있습니다.',requiresDocument:!!connection,
  async request(action,payload){if(ticket!==generation||connection!==live||!active)throw new Obsolete();if(!['catalog','document','chat','review','request-promotion','promote','revoke','revise'].includes(action))throw Error('현재 문서의 조회·확인·공유 작업만 사용할 수 있습니다.');if(connection&&['request-promotion','promote','revoke'].includes(action)&&live?.capabilities.workspace_sharing!==true)throw Error('현재 연결은 전사 공유를 지원하지 않습니다.');const {department,...body}=payload;if(!['app','device',...(connection?['data']:[])].includes(department))throw Error('조회할 부서를 확인하세요.');if(['review','request-promotion','promote','revoke','revise'].includes(action)&&department!==owner)throw Error('원문 부서에서 확인·공유 상태를 변경하세요.');await connect();if(action==='review')throw Error('검토 내용을 같은 문서에 저장한 뒤 별도로 완료하세요.');if(['request-promotion','promote'].includes(action)){const current=await request('kb','document',{id:body.id},department);if(current.version!==body.version)throw Error('문서 버전이 바뀌었습니다. 목록을 새로고침하세요.');if(!humanReview(current).current||current.state!=='confirmed')throw Error('현재 버전의 검토 기록을 저장하고 완료한 뒤 공유하세요.')}let result;try{result=await request('kb',action,body,department)}catch(error){if(connection&&error.visitorDenied)render();throw error}if(ticket!==generation||connection!==live||!active)throw new Obsolete();if(['review','request-promotion','promote','revoke','revise'].includes(action)&&state.document?.id===body.id){state.document=await linkedDocument(body.id);state.answer=null;await loadComparison();const summary=$('.company-context'),details=$('.company-context-details');if(summary)summary.outerHTML=compactTarget();if(details)details.outerHTML=contextDetails()}return result}
 }}
 function bind(){document.querySelectorAll('[data-company-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.companyAction;if(a.startsWith('step')){go(Number(a.slice(4)));return}if(a==='reviewer'){state.role='reviewer';render();return}if(a==='rebase-human-review'){if(state.humanDraft)state.humanDraft.version=state.document.version;render();return}if(a==='compose'){state.draft={content:initialContent(),valid_from:'2026-09-01',valid_to:'2026-12-31'};render();return}perform(async()=>{if(a==='open')await openSelected();if(a==='live-draft')await createLiveDraft();if(a==='catalog')await catalog();if(a==='refresh')await refreshDocument();if(a==='more')await search(true);if(a==='complete-human-review')await completeHumanReview();if(a==='new-session'){state.session=null;state.expired=false;resetContext();await connect();state.notice='새 격리 세션을 열었습니다. 이전 브라우저 기록은 그대로 보관합니다.'}})});
 document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>perform(()=>selectStation(Number(b.dataset.station))));
 const searchForm=$('#company-search');if(searchForm)searchForm.onsubmit=e=>{e.preventDefault();state.q=searchForm.elements.q.value.trim();state.chargerId=searchForm.elements.charger.value.trim();perform(()=>search())};
 const c=$('#company-charger');if(c)c.onchange=()=>{state.recordKey=c.value;resetContext();render()};const d=$('#company-department');if(d)d.onchange=()=>{state.department=d.value;state.question=defaultQuestion(state.department);resetContext();render();if(state.tab===5&&state.session)perform(catalog)};
 const save=$('#company-save');if(save){save.oninput=()=>{state.draft={content:save.elements.content.value,valid_from:save.elements.valid_from.value,valid_to:save.elements.valid_to.value}};save.onsubmit=e=>{e.preventDefault();const values={...state.draft};perform(()=>saveDraft(values))}};
 const human=$('#company-human-review');if(human){const boundVersion=state.humanDraft?.version??state.document.version;const values=()=>({version:boundVersion,outcome:human.elements.outcome.value,facts:human.elements.facts.value,conditions:human.elements.conditions.value,no_unknown:human.elements.no_unknown.checked,unknowns:human.elements.unknowns.value,next:human.elements.next.value,resolve_comment_ids:[...human.querySelectorAll('[name=resolve]:checked')].map(e=>e.value)});human.oninput=()=>{state.humanDraft={...values(),id:state.document.id};const complete=document.querySelector('[data-company-action=complete-human-review]');if(complete)complete.disabled=true};human.onsubmit=e=>{e.preventDefault();const input=values();perform(()=>saveHumanReview(input))}}
 const comment=$('#company-comment');if(comment){comment.oninput=()=>{state.commentDraft=comment.elements.body.value};comment.onsubmit=e=>{e.preventDefault();const body=comment.elements.body.value.trim();perform(()=>postComment(body))}};
 const role=$('#company-role');if(role)role.onchange=()=>{state.role=role.value;render()};const revise=$('#company-revise');if(revise){const values=()=>({content:revise.elements.content.value,reason:revise.elements.reason.value,department_identifier:revise.elements.department_identifier?.value.trim()||'',resolve_comment_ids:[...revise.querySelectorAll('[name=resolve]:checked')].map(x=>x.value)});revise.oninput=()=>{state.revisionDraft=values()};revise.onsubmit=e=>{e.preventDefault();const input=values();perform(()=>reviseDocument(input))}};
 document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>perform(async()=>{state.comparison=await request('kb','compare-versions',{id:state.document.id,from_version:Number(b.dataset.compare),to_version:state.document.version})}));
 const form=$('#company-ask');if(form){form.oninput=()=>{state.question=form.elements.question.value;state.asOf=form.elements.as_of.value;state.answerMode=(form.elements.answer_mode?.value||'knowledge');state.answer=null;document.querySelector('.company-answer')?.remove()};if(form.elements.answer_mode)form.elements.answer_mode.onchange=()=>{state.answerMode=form.elements.answer_mode.value;state.answer=null;render()};form.onsubmit=e=>{e.preventDefault();const values={question:form.elements.question.value.trim(),as_of:form.elements.as_of.value,answer_mode:(form.elements.answer_mode?.value||'knowledge'),generate:e.submitter?.dataset.generate==='true'};perform(()=>ask(values))}};
 document.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>perform(async()=>{const d=await request('kb','document',{id:b.dataset.document});if(live){if(!matches(d))throw Error('현재 선택 문맥과 다른 문서입니다.');state.document=d;await loadComparison();go(2);return}const s=d.source;if(s?.kind!=='company_charger_knowledge')throw Error('충전기 연결 정보가 없는 문서입니다.');state.station=s.station;state.recordKey=s.record_key;state.chargers=[{record_key:s.record_key,charger_id:s.public_charger_id}];state.source=s.public_source;resetContext();state.document=d;await loadComparison();go(2)}));
 const library=$('#company-shared-library');if(library){const controller=window.KnowHowOrganizationUI.createController({allowInquiry:true,adapter:sharedAdapter()});sharingView=controller.mount(library,{mode:'library'})}
 const materials=$('#company-materials');if(materials)materials.ontoggle=()=>{if(materials.open&&!sourceView&&window.KnowHowSourceRecords)sourceView=window.KnowHowSourceRecords.mount($('#company-source-records'),{store:window.KnowHowSourceRecords.createStore(),department:state.department})};
 }
 function activate(){if(live&&!liveRoute())closeLive();const entering=!active;if(!active){sessionGeneration++;token='';user=null;docs=[];selected=null;clearWorkflow();active=true}state.tab=Math.max(1,Math.min(5,Number(location.hash.match(/^#scenario-([1-5])(?:-live)?$/)?.[1]||1)));$('#session').hidden=true;$('#connection').textContent=(live||liveRoute())?'입수 원본과 연결된 개인 방문자 KB입니다. 담당자 역할은 이 방문자 공간의 검토 체험이며 실제 조직의 승인이 아닙니다.':'로그인 없는 격리 체험 공간입니다. 공개 충전소 원문과 가상 부서 지식을 사용하며 실제 회사 자료와 연결되지 않습니다.';document.querySelector('.workspace').innerHTML='KNOW:HOW<strong>충전 업무 지식</strong>';document.querySelector('.aside-note').textContent='대상 선택 → 문서 확인 → 정정 → 재사용';const nav=document.querySelector('nav');nav.hidden=false;nav.innerHTML=tabs.map((t,i)=>`<button data-scenario="${i+1}"><span class="scenario-number">0${i+1}</span>${t}</button>`).join('');nav.onclick=e=>{const b=e.target.closest('[data-scenario]');if(b)go(Number(b.dataset.scenario))};render();if(entering&&!liveRoute()&&state.session&&!state.loaded&&!state.expired)perform(async()=>{await catalog();const d=state.documents.find(matches);if(d){state.document=await request('kb','document',{id:d.id});await loadComparison()}});return refreshCollection()}
 function deactivate(){active=false;generation++;handoffSerial++;closeLive();sharingView?.();sharingView=null;sourceView?.destroy();sourceView=null}
 return {activate,deactivate,isActive:()=>active,openVisitorContext};
})();
window.KnowHowCompanyLive={open:sampleDemo.openVisitorContext};
window.KnowHowCompany={openVisitorContext:sampleDemo.openVisitorContext};
sampleDemo.activate();
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#scenario-'))sampleDemo.activate()});
