'use strict';
// Company workflow: one selected charger and one server document throughout.
const sampleDemo=(()=>{
 const fixture=window.KNOWHOW_EXAMPLE,legacyKey='knowhow.scenarios.v1';
 const apiBase=(window.KNOWHOW_CONFIG?.apiBase||'https://api.ctrl-j.xyz/knowhow').replace(/\/$/,'');
 const sessionKey='knowhow.company.session.v2:'+apiBase;
 const tabs=['문의할 대상 찾기','부서 문서 확인','댓글과 기준 정정','다음 사람이 조회','부서 KB 모음'];
 const dept=d=>d==='device'?'충전기개발팀':'앱개발팀',copy=v=>JSON.parse(JSON.stringify(v));
 const status=s=>({draft:'담당자 확인 대기',confirmed:'담당자 확인 완료',rejected:'반려'}[s]||s);
 let active=false,generation=0,sourceView=null;
 const state={tab:1,busy:false,error:'',notice:'',session:null,expired:false,department:'app',station:copy(fixture.station),chargers:copy(fixture.chargers),recordKey:fixture.selected_record_key,source:copy(fixture.source),q:'GS타워',chargerId:'01',stations:[copy(fixture.station)],total:1,document:null,documents:[],loaded:false,role:'member',question:'이 충전기의 앱 오류는 누구에게 어떤 정보를 전달해야 하나요?',asOf:'2026-09-21',answerMode:'knowledge',answer:null,answerQuestion:'',draft:null,comparison:null,comparisonError:'',commentDraft:'',revisionDraft:null};
 class Obsolete extends Error {}
 function charger(){return state.chargers.find(c=>c.record_key===state.recordKey)}
 function context(){return [state.station?.station_key,state.recordKey,state.department].join('|')}
 function matches(d){const s=d.source;return s?.kind==='company_charger_knowledge'&&s.station?.station_key===state.station?.station_key&&s.record_key===state.recordKey&&d.department===state.department}
 function fixtureId(){if(state.station?.station_key!==fixture.station.station_key||state.recordKey!==fixture.selected_record_key)return '';const m=fixture.inquiries[state.department].synthetic_mapping?.[0];return m?.[state.department==='app'?'app_charger_id':'device_charger_id']||''}
 function currentId(){return state.document?state.document.source?.department_identifier||'':fixtureId()}
 function remember(){try{localStorage.setItem(sessionKey,JSON.stringify({session:state.session,selection:{station:state.station,chargers:state.chargers,recordKey:state.recordKey,source:state.source,department:state.department}}))}catch{state.notice='이 기기에 연결 정보를 보관하지 못했습니다. 현재 탭에서는 계속할 수 있습니다.'}}
 function restore(){try{const saved=JSON.parse(localStorage.getItem(sessionKey)||'null');if(saved?.session){if(typeof saved.session!=='string')throw Error();state.session=saved.session;}const s=saved?.selection;if(s?.station?.station_key&&Array.isArray(s.chargers)&&s.chargers.some(c=>c.record_key===s.recordKey)&&['app','device'].includes(s.department))Object.assign(state,s)}catch{state.error='이전 연결 정보를 읽지 못했습니다. 저장된 기록은 변경하지 않았습니다.'}}
 restore();
 async function request(group,action,payload={}){const ticket=generation;const response=await fetch(apiBase+'/demo/'+group+'/'+action,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify(group==='kb'&&action!=='session'?{session_id:state.session,org:'alpha',department:state.department,sample_pack:'company',...payload}:payload),signal:AbortSignal.timeout(60000)}).catch(()=>{if(ticket!==generation||!active)throw new Obsolete();throw Error('서버에 연결하지 못했습니다. 입력을 유지했습니다. 다시 시도해 주세요.')});const result=await response.json();if(ticket!==generation||!active)throw new Obsolete();if(!response.ok){if(response.status===401&&group==='kb')state.expired=true;throw Error(result.error||'요청을 처리하지 못했습니다. 다시 시도해 주세요.')}return result}
 async function connect(){if(state.expired)throw Error('체험 세션이 만료되었습니다. 새 세션을 열어 주세요.');if(state.session)return;const r=await request('kb','session',{sample_pack:'company'});if(!r.session_id)throw Error('세션 응답을 확인할 수 없습니다.');state.session=r.session_id;remember()}
 async function catalog(){await connect();const r=await request('kb','catalog',{scope:'department'});state.documents=r.documents||[];state.loaded=true;return state.documents}
 async function openSelected(){await catalog();const d=state.documents.find(matches);state.document=d?await request('kb','document',{id:d.id}):null;await loadComparison();state.answer=null;state.draft=null;state.tab=2;setHash();if(!d)state.notice='선택한 충전기에 연결된 부서 문서가 없습니다. 확인할 내용을 초안으로 남길 수 있습니다.'}
 async function refreshDocument(){if(!state.document)return;const d=await request('kb','document',{id:state.document.id});if(!matches(d))throw Error('선택한 충전기와 문서의 출처가 다릅니다. 대상을 다시 선택해 주세요.');state.document=d;await loadComparison();return d}
 async function loadComparison(){state.comparison=null;state.comparisonError='';const d=state.document;if(d&&d.version>1){const previous=(d.history||[]).filter(v=>v.version<d.version).sort((a,b)=>b.version-a.version)[0];if(previous)try{state.comparison=await request('kb','compare-versions',{id:d.id,from_version:previous.version,to_version:d.version})}catch(e){if(e instanceof Obsolete)throw e;state.comparisonError='현재 문서는 불러왔지만 전후 비교를 불러오지 못했습니다. 최신 버전을 새로고침해 주세요.'}}}

 async function perform(fn){if(state.busy)return;state.busy=true;state.error='';state.notice='';render();try{await fn()}catch(e){if(!(e instanceof Obsolete))state.error=e.message}finally{state.busy=false;render()}}
 function resetContext(){generation++;state.document=null;state.documents=[];state.loaded=false;state.answer=null;state.draft=null;state.comparison=null;state.commentDraft='';state.revisionDraft=null;state.error='';state.notice='';remember()}
 function setHash(){history.replaceState(null,'','#scenario-'+state.tab)}
 function go(tab){state.tab=tab;setHash();render();window.scrollTo?.(0,0);if(tab===5&&state.session&&!state.busy)perform(catalog)}
 function button(label,action,extra=''){return `<button data-company-action="${action}" ${state.busy?'disabled':''} ${extra}>${label}</button>`}
 function target(){const c=charger(),id=currentId(),d=state.document;return `<section class="company-target card" aria-label="현재 문의 대상"><div class="eyebrow">${esc(dept(state.department))} 문의 대상</div><h2 class="company-target-id">${esc(id||'내부 ID 확인 필요')}</h2><p>${id?d?`부서 KB에서 가져온 ID · v${esc(d.version)} · ${esc(status(d.state))}`:'준비된 연결표의 체험용 ID · 부서 KB 확인 전':'공공 ID에 대응하는 부서 ID가 연결되어 있지 않습니다.'}</p><dl class="company-facts"><dt>공공 충전기 ID</dt><dd><strong>${esc(c?.charger_id||'선택 필요')}</strong></dd><dt>충전소</dt><dd>${esc(state.station?.name||'선택 필요')}</dd><dt>주소</dt><dd>${esc(state.station?.address||'미제공')}</dd><dt>운영사</dt><dd>${esc(state.station?.operator||'미제공')}</dd></dl>${state.tab===1?`<div class="company-target-actions"><div class="grid"><label>충전기<select id="company-charger" ${state.busy?'disabled':''}>${state.chargers.map(c=>`<option value="${esc(c.record_key)}" ${c.record_key===state.recordKey?'selected':''}>공공 ID ${esc(c.charger_id)} · ${esc(c.type||'형식 미제공')}</option>`).join('')}</select></label><label>담당 부서<select id="company-department" ${state.busy?'disabled':''}><option value="app" ${state.department==='app'?'selected':''}>앱개발팀</option><option value="device" ${state.department==='device'?'selected':''}>충전기개발팀</option></select></label></div>${button('이 충전기의 부서 KB 열기','open','class="primary"')}</div>`:''}${d?`<p class="company-doc-link">같은 문서로 이어집니다 · <code>${esc(d.id)}</code> · v${esc(d.version)}</p>`:''}</section>`}
 function sourceInfo(d){const s=d?.source||draftSource(),p=s.public_source||state.source||{};return `<details class="company-source"><summary>출처·데이터 안내</summary><p>공개 원문은 충전소·주소·운영사·공공 ID의 근거입니다. 내부 연결표와 역할은 격리된 체험 데이터이며 실제 내부 매핑이나 조직 승인을 뜻하지 않습니다.</p><dl class="company-facts"><dt>원본 행</dt><dd>${esc(s.record_key||state.recordKey)}</dd><dt>수집 시각</dt><dd>${esc(p.collection_finished_at||p.collected_at||'미제공')}</dd><dt>자료 범위</dt><dd>${esc(p.dataset_scope||p.snapshot_kind||'공개 원문 보존본')}</dd><dt>원문</dt><dd>${esc(p.source_url||'출처 URL 미제공')}</dd></dl></details>`}
 function draftSource(){return {kind:'company_charger_knowledge',station:copy(state.station),record_key:state.recordKey,public_charger_id:charger()?.charger_id||'',department:state.department,public_source:copy(state.source),mapping_status:fixtureId()?'synthetic_fixture':'unconfirmed',department_identifier:fixtureId(),synthetic:true}}
 function initialContent(){const id=fixtureId(),c=charger();return `${dept(state.department)} 문의 기준\n\n대상: ${state.station.name} / 공공 충전기 ID ${c?.charger_id||''}\n주소: ${state.station.address.trim()}\n운영사: ${state.station.operator}\n\n${id?`부서 문의 ID: ${id}\n공개 ID·주소·운영사로 같은 대상인지 대조합니다.`:'부서 내부 ID: 확인 필요\n공공 ID만으로 내부 장비를 특정하지 않습니다. 담당 부서에 연결 근거와 ID를 확인합니다.'}\n\n전달할 정보\n${state.department==='app'?'앱 오류 화면, 발생 시각, 오류 코드':'장비 증상, 발생 시각, 장비 로그'}\n공공 충전기 ID, 충전소 주소, 운영사, 원본 행 참조\n\n적용 조건\n${id?'체험용 연결표의 문의 절차입니다. 실제 대응 관계는 별도 확인이 필요합니다.':'내부 대응 관계와 적용 기간을 확인한 뒤 기준을 확정합니다.'}`}
 function documentBody(d){return `<section class="card company-document"><div class="row"><h2>${esc(d.title)}</h2><span class="badge">v${esc(d.version)} · ${esc(status(d.state))}</span></div><dl class="company-facts"><dt>담당 부서</dt><dd>${esc(dept(d.department))}</dd><dt>적용일</dt><dd>${esc(d.valid_from||'미등록')} ~ ${esc(d.valid_to||'미등록')}</dd><dt>문서 ID</dt><dd><code>${esc(d.id)}</code></dd></dl><pre class="company-body">${esc(d.content)}</pre>${sourceInfo(d)}${comments(d)}${button('최신 버전 새로고침','refresh')}</section>`}
 function comments(d){return `<section class="company-comments" aria-label="문서 댓글"><h3>댓글과 처리 상태</h3>${(d.comments||[]).map(c=>`<article class="company-comment"><div class="row"><strong>${c.author_role==='reviewer'?'담당자':'구성원'} · v${esc(c.version)}</strong><span class="badge">${c.resolved_version?'v'+esc(c.resolved_version)+'에 반영':c.pending_version?'v'+esc(c.pending_version)+'에 반영 예정 · 확인 대기':'확인 대기'}</span></div><p>${esc(c.body)}</p></article>`).join('')||'<p>아직 댓글이 없습니다.</p>'}</section>`}
 function historyMarkup(d){const pair=state.comparison,rows=pair?[pair.after,pair.before]:[d];return `<section class="card company-history"><h2>정정 전후와 버전 이력</h2>${state.comparisonError?`<p role="alert">${esc(state.comparisonError)}</p>`:''}${rows.map((v,i)=>`<article><h3>${pair?(i===0?'정정 후':'정정 전'):'현재 기준'} · v${esc(v.version)} · ${esc(status(v.state))}</h3><p><strong>변경 이유</strong> ${esc(v.reason||'최초 등록')}</p><pre class="company-body">${esc(v.content)}</pre></article>`).join('')}<p>보관된 버전: ${(d.history||[]).map(v=>'v'+esc(v.version)).join(' → ')||'v'+d.version}</p>${(d.history||[]).filter(v=>v.version<d.version).map(v=>`<button data-compare="${v.version}" ${state.busy?'disabled':''}>v${v.version}와 현재 버전 비교</button>`).join('')}</section>`}

 function emptyDocument(){if(!state.station||!charger())return `<section class="card"><h2>충전기를 먼저 선택하세요</h2>${button('문의 대상 찾기로 이동','step1')}</section>`;return `<section class="card"><h2>선택한 충전기의 부서 문서</h2><p>${state.loaded?'연결된 문서가 없습니다. 확인할 내용을 먼저 초안으로 남기세요.':'같은 충전기와 부서에 연결된 서버 KB를 확인하세요.'}</p>${button('선택한 충전기의 부서 KB 열기','open','class="primary"')}${state.loaded?button('문서 초안 작성하기','compose'):''}</section>`}
 function searchView(){return `<form id="company-search" class="card"><h2>다른 충전소 찾기</h2><div class="grid"><label>지역·주소·건물명<input name="q" value="${esc(state.q)}" required></label><label>공공 충전기 ID (선택)<input name="charger" value="${esc(state.chargerId)}"></label></div><button class="primary" ${state.busy?'disabled':''}>충전소 검색</button><p class="muted">공개 원문에서 대상을 찾습니다. 검색 범위와 수집 시각은 출처에서 확인할 수 있습니다.</p></form><section class="card"><h2>충전소 후보 · ${state.total}개</h2>${state.stations.map((s,i)=>`<button class="station-option" data-station="${i}" ${state.busy?'disabled':''}><strong>${esc(s.name)}</strong><span>${esc(s.address)}</span><small>${esc(s.operator)}</small></button>`).join('')||'<p>검색 결과가 없습니다. 주소나 건물명을 바꿔 주세요.</p>'}${state.stations.length<state.total?button('후보 더 보기','more'):''}</section>${state.station?`<section class="card"><h2>문의할 때 전달할 항목</h2><ul><li><strong>대상 확인:</strong> 부서 ID, 공공 ID, 충전소 주소, 운영사</li><li><strong>문제 설명:</strong> ${state.department==='app'?'앱 오류 화면·발생 시각·오류 코드':'장비 증상·발생 시각·장비 로그'}</li><li><strong>확인 요청:</strong> 같은 대상인지, 사용할 기준과 적용 기간</li></ul>${sourceInfo(state.document)}</section>`:''}`}
 function compose(){const draft=state.draft||{content:initialContent(),valid_from:'2026-09-01',valid_to:'2026-12-31'};return `<form id="company-save" class="card"><h2>확인할 내용을 부서 문서로 남기기</h2><p>문의 내용은 초안으로 저장됩니다. 담당자 확인을 마쳐야 다음 사람이 근거로 조회할 수 있습니다.</p><label>문서 본문<textarea name="content" rows="12" required>${esc(draft.content)}</textarea></label><div class="grid"><label>적용 시작<input name="valid_from" type="date" value="${esc(draft.valid_from)}" required></label><label>적용 종료<input name="valid_to" type="date" value="${esc(draft.valid_to)}" required></label></div><button class="primary" ${state.busy?'disabled':''}>부서 KB에 초안 저장</button></form>`}
 function captureView(){return state.document?documentBody(state.document)+`<div class="actions">${button('댓글·정정으로 이어가기','step3','class="primary"')}</div>`:emptyDocument()+(state.draft?compose():'')}
 function correctView(){const d=state.document;if(!d)return emptyDocument();return documentBody(d)+`<form id="company-comment" class="card"><h2>빠진 조건이나 오류 알리기</h2><label>문서에 남길 댓글<textarea name="body" required maxlength="1000" rows="3">${esc(state.commentDraft)}</textarea></label><button ${state.busy?'disabled':''}>댓글 남기기</button></form><section class="card"><h2>담당자가 기준 확인·정정</h2><label>현재 역할<select id="company-role" ${state.busy?'disabled':''}><option value="member" ${state.role==='member'?'selected':''}>문의하는 구성원</option><option value="reviewer" ${state.role==='reviewer'?'selected':''}>담당자 역할로 검토</option></select></label>${state.role==='reviewer'?`${d.state!=='confirmed'?button('현재 버전 확인 완료','review','class="primary"'):''}<form id="company-revise"><label>정정할 본문<textarea name="content" rows="12" required>${esc(state.revisionDraft?.content??d.content)}</textarea></label><label>상단에 표시할 부서 ID<input name="department_identifier" value="${esc(state.revisionDraft?.department_identifier??d.source?.department_identifier??'')}" maxlength="100" placeholder="연결 근거가 없으면 비워 두세요"></label><p class="muted">본문의 ID를 정정했다면 이 항목도 함께 바꾸세요. 미연결 대상에는 ID를 추정해 넣지 않습니다.</p><label>변경 이유<input name="reason" value="${esc(state.revisionDraft?.reason||'')}" required maxlength="1000"></label>${(d.comments||[]).filter(c=>!c.resolved_version).map(c=>`<label class="check"><input type="checkbox" name="resolve" value="${esc(c.id)}">이 댓글 반영: ${esc(c.body)}</label>`).join('')}<p>정정본은 새 버전의 초안입니다. 확인 완료 후 다음 사람의 조회에 반영됩니다.</p><button class="primary" ${state.busy?'disabled':''}>정정본을 새 버전으로 저장</button></form>`:'<p>댓글을 남긴 뒤 담당자 역할로 전환하면 정정 과정을 이어볼 수 있습니다.</p>'}</section>${historyMarkup(d)}${button('다음 사람이 최신 기준 조회','step4')}`}
 function answerMarkup(){const r=state.answer;if(!r)return '';return `<section class="card company-answer"><h2>${r.ai_generated?'답변':'조회한 원문 근거'}</h2><p><strong>질문</strong> ${esc(state.answerQuestion)}</p>${r.ai_generated?`<span class="badge">${String(r.ai?.status||'').includes('모의')?'모의 응답 · 실제 모델 호출 없음':'AI 생성 · 원문 대조 필요'}</span><pre class="company-body">${esc(r.answer)}</pre>`:`<p>${esc(r.error_code||r.ai?.error_code?'답변 생성을 완료하지 못했습니다. 아래 원문 근거를 확인해 주세요.':'AI를 생성하지 않고 선택한 문서의 원문을 확인했습니다.')}</p>`}${(r.evidence||[]).map(e=>`<article class="company-evidence"><h3>${esc(e.title||e.name||'문서 근거')} · v${esc(e.version)}</h3><p>${esc(dept(e.department||state.department))} · 문서 ${esc(e.id||e.document_id||state.document?.id)}</p><pre class="company-body">${esc(e.text||e.content||e.snippet||'')}</pre></article>`).join('')||'<p>현재 적용일에 사용할 확인된 근거가 없습니다.</p>'}</section>`}
 function reuseView(){const d=state.document;if(!d)return emptyDocument();return documentBody(d)+`<form id="company-ask" class="card"><h2>같은 최신 문서에 질문하기</h2><p>조회 대상: <strong>${esc(d.title)} · v${esc(d.version)}</strong></p><label>질문<textarea name="question" required maxlength="1000" rows="3">${esc(state.question)}</textarea></label><div class="grid"><label>업무 적용일<input type="date" name="as_of" value="${esc(state.asOf)}" required></label><label>요청할 내용<select name="answer_mode"><option value="knowledge" ${state.answerMode==='knowledge'?'selected':''}>기준 설명</option><option value="inquiry" ${state.answerMode==='inquiry'?'selected':''}>담당자에게 보낼 문의 초안</option></select></label></div><div class="actions"><button data-generate="false" ${state.busy||d.state!=='confirmed'?'disabled':''}>근거만 확인</button><button class="primary" data-generate="true" ${state.busy||d.state!=='confirmed'||window.KNOWHOW_CONFIG?.aiRequestsPaused!==false?'disabled':''}>AI에 질문하기</button></div>${d.state!=='confirmed'?'<p>담당자가 현재 버전의 확인을 완료해야 조회할 수 있습니다.</p>':''}<p class="muted">AI 요청은 생성 버튼을 누를 때만 실행됩니다. 문서 이동·댓글·원문 조회는 AI를 호출하지 않습니다.</p></form>${answerMarkup()}${button('부서 KB 목록에서 확인','step5')}`}
 function legacy(){try{const rows=JSON.parse(localStorage.getItem(legacyKey)||'[]');if(!Array.isArray(rows))throw Error();return rows.length?`<details class="card"><summary>이전에 이 기기에 저장한 기록 ${rows.length}개</summary><p>서버 문서와 별도로 보관된 이전 기록입니다.</p>${rows.map(d=>`<article><h3>${esc(d.name||d.id)}</h3>${(d.versions||[]).map(v=>`<h4>v${esc(v.version)}</h4><pre class="company-body">${esc(v.content)}</pre>`).join('')}${(d.comments||[]).map(c=>`<p>댓글: ${esc(c.body)}</p>`).join('')}</article>`).join('')}</details>`:''}catch{return '<p>이전 저장 기록을 읽지 못했습니다. 원본은 변경하지 않았습니다.</p>'}}
 function collectionView(){return `<section class="card"><h2>${esc(dept(state.department))} KB</h2><label>부서<select id="company-department" ${state.busy?'disabled':''}><option value="app" ${state.department==='app'?'selected':''}>앱개발팀</option><option value="device" ${state.department==='device'?'selected':''}>충전기개발팀</option></select></label><p>현재 격리 세션의 부서 문서입니다. 같은 문서를 열어 댓글·정정·조회를 이어갑니다.</p>${button('부서 문서 목록 새로고침','catalog','class="primary"')}${state.documents.filter(d=>d.source?.kind==='company_charger_knowledge').map(d=>`<article class="company-library-row"><h3>${esc(d.title)}</h3><p>${esc(d.source.station?.name)} · 공공 ID ${esc(d.source.public_charger_id)} · v${esc(d.version)} · ${esc(status(d.state))}</p><p><code>${esc(d.id)}</code></p><button data-document="${esc(d.id)}" ${state.busy?'disabled':''}>이 문서 열기</button></article>`).join('')||'<p>목록을 열어 연결된 문서를 확인하세요.</p>'}</section>${legacy()}<details id="company-materials" class="card"><summary>별도 자료 추가 · TXT/MD</summary><p>추가 자료를 이 기기에서 읽습니다. 선택한 서버 문서에 자동으로 합쳐지지 않습니다.</p><div id="company-source-records"></div></details>`}
 function render(){if(!active)return;sourceView?.destroy();sourceView=null;const views=[searchView,captureView,correctView,reuseView,collectionView];$('#page').innerHTML=`<div class="company-workflow"><div class="eyebrow">KNOWLEDGE · 0${state.tab}</div><h1>${tabs[state.tab-1]}</h1>${state.station?target():''}${state.error?`<p class="notice" role="alert">${esc(state.error)}</p>`:''}${state.expired?button('새 격리 세션 열기','new-session'):''}<p role="status">${esc(state.notice)}</p>${views[state.tab-1]()}</div>`;document.querySelectorAll('[data-scenario]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.scenario)===state.tab);b.setAttribute('aria-current',Number(b.dataset.scenario)===state.tab?'page':'false')});bind()}
 async function search(append=false){const r=await request('workflow','search',{q:state.q,charger_id:state.chargerId,limit:20,offset:append?state.stations.length:0});state.stations=append?[...state.stations,...r.stations]:r.stations;state.total=r.total;state.source=r.source;if(!append){state.station=null;state.chargers=[];state.recordKey='';resetContext()}}
 async function selectStation(i){const s=state.stations[i],r=await request('workflow','chargers',{station_key:s.station_key,limit:50,offset:0});state.station=r.station;state.chargers=r.chargers;state.recordKey=r.chargers[0]?.record_key||'';state.source=r.source;resetContext()}
 async function saveDraft(values){await catalog();const existing=state.documents.find(matches);if(existing){state.document=await request('kb','document',{id:existing.id});throw Error('같은 대상의 문서가 이미 있습니다. 기존 문서를 열었습니다. 정정 기능을 이용해 주세요.')}if(values.valid_from>values.valid_to)throw Error('적용 기간 순서를 확인하세요.');const r=await request('kb','save',{title:state.station.name+' · 공공 ID '+charger().charger_id+' · '+dept(state.department)+' 문의 기준',...values,source:draftSource(),identifiers:fixtureId()?[fixtureId()]:[],visibility:'department'});state.document=await request('kb','document',{id:r.id});state.draft=null;state.notice='부서 KB에 초안으로 저장했습니다. 같은 문서에서 댓글과 담당자 확인을 이어갑니다.'}
 async function ask(values){state.question=values.question;state.asOf=values.as_of;state.answerMode=values.answer_mode;await refreshDocument();if(state.document.state!=='confirmed')throw Error('최신 버전의 담당자 확인이 필요합니다.');if(values.generate&&window.KNOWHOW_CONFIG?.aiRequestsPaused!==false)throw Error('현재 AI 생성 요청을 사용할 수 없습니다.');state.answer=null;const r=await request('kb','chat',{...values,document_id:state.document.id,include_company:false});state.answer=r;state.answerQuestion=values.question}
 async function postComment(body){state.commentDraft=body;const r=await request('kb','comment',{id:state.document.id,version:state.document.version,body,author_role:state.role});state.document.comments=r.comments||[...(state.document.comments||[]),r.comment];state.commentDraft='';state.notice='댓글을 문서 아래에 남겼습니다. 담당자 확인 대기 중입니다.'}
 async function reviseDocument(values){if(state.role!=='reviewer')throw Error('담당자 역할로 전환하세요.');state.revisionDraft=values;const d=state.document,{department_identifier,...fields}=values;const source={...d.source,department_identifier,mapping_status:department_identifier===d.source?.department_identifier?d.source.mapping_status:department_identifier?'user_provided_unverified':'unconfirmed'};await request('kb','revise',{id:d.id,version:d.version,...fields,source,identifiers:department_identifier?[department_identifier]:[]});await refreshDocument();state.revisionDraft=null;state.answer=null;state.notice='정정본을 새 초안 버전으로 저장했습니다. 아래에서 전후 본문을 확인하고 현재 버전의 확인을 완료하세요.'}
 async function reviewDocument(){if(state.role!=='reviewer')throw Error('담당자 역할로 전환하세요.');await request('kb','review',{id:state.document.id,version:state.document.version,state:'confirmed',reason:state.document.reason||'담당자 역할로 본문과 적용 조건 확인'});await refreshDocument();state.answer=null;state.notice='현재 버전의 확인을 완료했습니다. 다음 조회부터 이 버전을 사용합니다.'}
 function bind(){document.querySelectorAll('[data-company-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.companyAction;if(a.startsWith('step')){go(Number(a.slice(4)));return}if(a==='compose'){state.draft={content:initialContent(),valid_from:'2026-09-01',valid_to:'2026-12-31'};render();return}perform(async()=>{if(a==='open')await openSelected();if(a==='catalog')await catalog();if(a==='refresh')await refreshDocument();if(a==='more')await search(true);if(a==='review')await reviewDocument();if(a==='new-session'){state.session=null;state.expired=false;resetContext();await connect();state.notice='새 격리 세션을 열었습니다. 이전 브라우저 기록은 그대로 보관합니다.'}})});
 document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>perform(()=>selectStation(Number(b.dataset.station))));
 const searchForm=$('#company-search');if(searchForm)searchForm.onsubmit=e=>{e.preventDefault();state.q=searchForm.elements.q.value.trim();state.chargerId=searchForm.elements.charger.value.trim();perform(()=>search())};
 const c=$('#company-charger');if(c)c.onchange=()=>{state.recordKey=c.value;resetContext();render()};const d=$('#company-department');if(d)d.onchange=()=>{state.department=d.value;state.question=`이 충전기의 ${state.department==='app'?'앱 오류':'장비 이상'}는 누구에게 어떤 정보를 전달해야 하나요?`;resetContext();render();if(state.tab===5&&state.session)perform(catalog)};
 const save=$('#company-save');if(save){save.oninput=()=>{state.draft={content:save.elements.content.value,valid_from:save.elements.valid_from.value,valid_to:save.elements.valid_to.value}};save.onsubmit=e=>{e.preventDefault();const values={...state.draft};perform(()=>saveDraft(values))}};
 const comment=$('#company-comment');if(comment){comment.oninput=()=>{state.commentDraft=comment.elements.body.value};comment.onsubmit=e=>{e.preventDefault();const body=comment.elements.body.value.trim();perform(()=>postComment(body))}};
 const role=$('#company-role');if(role)role.onchange=()=>{state.role=role.value;render()};const revise=$('#company-revise');if(revise){const values=()=>({content:revise.elements.content.value,reason:revise.elements.reason.value,department_identifier:revise.elements.department_identifier.value.trim(),resolve_comment_ids:[...revise.querySelectorAll('[name=resolve]:checked')].map(x=>x.value)});revise.oninput=()=>{state.revisionDraft=values()};revise.onsubmit=e=>{e.preventDefault();const input=values();perform(()=>reviseDocument(input))}};
 document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>perform(async()=>{state.comparison=await request('kb','compare-versions',{id:state.document.id,from_version:Number(b.dataset.compare),to_version:state.document.version})}));
 const form=$('#company-ask');if(form){form.oninput=()=>{state.question=form.elements.question.value;state.asOf=form.elements.as_of.value;state.answerMode=form.elements.answer_mode.value;state.answer=null;document.querySelector('.company-answer')?.remove()};form.onsubmit=e=>{e.preventDefault();const values={question:form.elements.question.value.trim(),as_of:form.elements.as_of.value,answer_mode:form.elements.answer_mode.value,generate:e.submitter?.dataset.generate==='true'};perform(()=>ask(values))}};
 document.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>perform(async()=>{const d=await request('kb','document',{id:b.dataset.document});const s=d.source;if(s?.kind!=='company_charger_knowledge')throw Error('충전기 연결 정보가 없는 문서입니다.');state.station=s.station;state.recordKey=s.record_key;state.chargers=[{record_key:s.record_key,charger_id:s.public_charger_id}];state.source=s.public_source;resetContext();state.document=d;await loadComparison();go(2)}));
 const materials=$('#company-materials');if(materials)materials.ontoggle=()=>{if(materials.open&&!sourceView&&window.KnowHowSourceRecords)sourceView=window.KnowHowSourceRecords.mount($('#company-source-records'),{store:window.KnowHowSourceRecords.createStore(),department:state.department})};
 }
 function activate(){const entering=!active;if(!active){sessionGeneration++;token='';user=null;docs=[];selected=null;clearWorkflow();active=true}state.tab=Math.max(1,Math.min(5,Number(location.hash.match(/^#scenario-([1-5])$/)?.[1]||1)));$('#session').hidden=true;$('#connection').textContent='로그인 없는 격리 체험 공간입니다. 공개 충전소 원문과 가상 부서 지식을 사용하며 실제 회사 자료와 연결되지 않습니다.';document.querySelector('.workspace').innerHTML='KNOW:HOW<strong>충전 업무 지식</strong>';document.querySelector('.aside-note').textContent='대상 선택 → 문서 확인 → 정정 → 재사용';const nav=document.querySelector('nav');nav.hidden=false;nav.innerHTML=tabs.map((t,i)=>`<button data-scenario="${i+1}"><span class="scenario-number">0${i+1}</span>${t}</button>`).join('');nav.onclick=e=>{const b=e.target.closest('[data-scenario]');if(b)go(Number(b.dataset.scenario))};render();if(entering&&state.session&&!state.loaded&&!state.expired)perform(async()=>{await catalog();const d=state.documents.find(matches);if(d){state.document=await request('kb','document',{id:d.id});await loadComparison()}})}
 function deactivate(){active=false;generation++;sourceView?.destroy();sourceView=null}
 return {activate,deactivate,isActive:()=>active};
})();
sampleDemo.activate();
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#scenario-'))sampleDemo.activate()});
