/* Isolated public organization-role demo. No protected account token is accepted. */
(function(root){'use strict';
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const name=value=>({app:'앱개발팀',device:'충전기개발팀',operations:'운영지원팀',data:'데이터운영팀',hr:'인사운영팀'}[value]||String(value));
 const stateName=value=>({draft:'초안',confirmed:'확인',rejected:'거절',approved:'전사 공유 승인',stale:'재승인 필요',pending:'승인 대기',requested:'승인 요청됨',none:'미공유'}[value]||value||'미공유');
 class ObsoleteContext extends Error {}
 function createController({apiBase,getSourceDrafts=()=>[],samplePack='company'}={}){
  let container=null,view='chat',epoch=0,pendingDraft=null;
  const availableDrafts=()=>pendingDraft?[pendingDraft,...getSourceDrafts().filter(d=>d.id!==pendingDraft.id)]:getSourceDrafts();
  const state={session:null,organizations:['alpha','beta'],departments:samplePack==='general'?['operations','data','hr']:['app','device'],org:'alpha',department:samplePack==='general'?'operations':'app',includeCompany:false,asOf:'2026-09-21',scope:'department',purpose:'read',documents:[],vector:null,error:'',notice:'',busy:false,connecting:false,history:new Map(),chatDraft:{question:'',exact:'',generate:false},editor:null,selected:null};
  const aiPaused=()=>root.KNOWHOW_CONFIG?.aiRequestsPaused!==false;
  const historyKey=()=>[state.session,state.org,state.department,state.includeCompany?'company':'department',state.asOf].join('|');
  const conversation=()=>{const key=historyKey();if(!state.history.has(key))state.history.set(key,{id:null,turns:[]});return state.history.get(key)};
  async function request(action,payload={},scoped=true){for(const [field,limit] of [['question',2000],['content',7000],['source',4000]]){if(payload[field]!==undefined&&new TextEncoder().encode(typeof payload[field]==='string'?payload[field]:JSON.stringify(payload[field])).length>limit)throw Error(`${field==='question'?'질문':field==='content'?'본문':'출처 정보'}은 UTF-8 기준 ${limit.toLocaleString()}바이트 이하여야 합니다.`)}const generation=epoch;const response=await fetch((apiBase||'https://api.ctrl-j.xyz/knowhow')+'/demo/kb/'+action,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({...scoped?{session_id:state.session,org:state.org,department:state.department,sample_pack:samplePack}:{},...payload}),signal:AbortSignal.timeout(60000)});const body=await response.json();if(generation!==epoch)throw new ObsoleteContext();if(!response.ok)throw Error(body.error||body.message||`요청 실패 (${response.status})`);return body}
  function identity(value){return typeof value==='string'?{id:value,name:value}:{id:value.id||value.org||value.department,name:value.name||value.label||value.id}}
  function currentDocument(id){return state.documents.find(d=>String(d.id)===String(id))}
  async function perform(task){if(state.busy)return;state.busy=true;state.error='';state.notice='';render();try{await task()}catch(error){if(!(error instanceof ObsoleteContext))state.error=error.message}finally{state.busy=false;render()}}
  async function connect(){if(state.session)return;state.connecting=true;render();try{const result=await request('session',{sample_pack:samplePack},false);if(!result.session_id)throw Error('샘플 세션 응답을 확인할 수 없습니다.');state.session=result.session_id;state.organizations=result.organizations||state.organizations;state.departments=result.departments||state.departments;state.org=identity(state.organizations[0]).id;if(!state.departments.some(d=>identity(d).id===state.department))state.department=identity(state.departments[0]).id;state.notice=result.notice||'가상 조직 체험 세션을 연결했습니다.';await catalog()}finally{state.connecting=false}}
  async function catalog(){const result=await request('catalog',{scope:state.scope});state.documents=result.documents||[];state.selected=null;state.vector=result.vector||null}
  function changeScope(changes){epoch++;if((changes.org&&changes.org!==state.org)||(changes.department&&changes.department!==state.department))state.chatDraft={question:'',exact:'',generate:false};if(changes.department&&changes.department!==state.department)pendingDraft=null;Object.assign(state,changes);state.documents=[];state.vector=null;state.editor=null;state.selected=null;state.error='';state.notice='';render()}
  function vectorMarkup(){if(!state.vector)return '<span class="badge">벡터 검색 상태 미확인</span>';const v=state.vector;return `<span class="badge">검색 상태: ${esc(v.status||'미확인')}</span><details><summary>검색 API 연결 정보</summary><p>저장소 ${esc(v.backend||'미제공')} · 임베딩 ${esc(v.model||'미제공')}</p><p class="muted">연결 상태와 의미 검색 품질은 별개입니다. 모의 응답을 실제 의미 검색으로 표시하지 않습니다.</p></details>`}
  function controls(){return `<div class="grid"><label>가상 조직<select data-org-control="org">${state.organizations.map(value=>{const o=identity(value);return `<option value="${esc(o.id)}" ${state.org===o.id?'selected':''}>${esc(o.name)}</option>`}).join('')}</select></label><label>내 부서 역할<select data-org-control="department">${state.departments.map(value=>{const d=identity(value);return `<option value="${esc(d.id)}" ${state.department===d.id?'selected':''}>${esc(name(d.name))}</option>`}).join('')}</select></label></div>`}
  function sourceLabel(source){if(typeof source==='string')return source;return source?.title||source?.label||source?.filename||source?.kind||'출처 상세 미제공'}
  function provenance(source){if(!source||typeof source!=='object')return `<p class="muted">출처 ${esc(sourceLabel(source))}</p>`;return `<details><summary>출처 상세 · 파일·입수 시각·참조 줄</summary><dl class="source-record-meta"><dt>출처</dt><dd>${esc(sourceLabel(source))}</dd><dt>파일명</dt><dd>${esc(source.filename||'미제공')}</dd><dt>입수 시각</dt><dd>${esc(source.collected_at||source.collectedAt||'미제공')}</dd><dt>원문 SHA-256</dt><dd>${esc(source.sha256||'미제공')}</dd><dt>참조 위치</dt><dd>${(source.citations||[]).map(c=>`${esc(c.recordId||c.record_id||'원문')} · ${esc(c.startLine??c.start_line)}–${esc(c.endLine??c.end_line)}줄`).join('<br>')||'미제공'}</dd></dl></details>`}
  function evidenceMarkup(rows){return rows.map(e=>`<article class="evidence"><strong>${e.citation_number?'['+esc(e.citation_number)+'] ':''}${esc(e.title||e.name||'근거 문서')}</strong><p class="muted">원부서 ${esc(name(e.department||e.source_department||'미제공'))} · v${esc(e.version)} · ${esc(e.scope||e.visibility||'범위 미제공')} · ${esc(stateName(e.state))}</p><p>${esc(e.text||e.content||e.snippet||'본문 미제공')}</p>${provenance(e.source)}<p class="muted">검색 ${esc(e.match||'미제공')}</p></article>`).join('')}
  function responseMarkup(result){const evidence=result.evidence||[];return `${result.ai_generated===true&&result.answer?`<span class="badge warn">실제 AI 생성 · 검토가 필요한 초안</span><div class="answer">${esc(result.answer)}</div>`:`<span class="badge">AI 생성 안 함</span><p>${esc(result.notice||result.status||'현재 범위의 검색 근거를 확인하세요.')}</p>${result.answer?`<div class="answer">${esc(result.answer)}</div>`:''}`}${evidence.length?`<details open><summary>검색 근거 · 원부서와 버전</summary>${evidenceMarkup(evidence)}</details>`:'<p class="notice">이 범위에서 사용할 근거를 찾지 못했습니다. 없는 내용을 답으로 확정하지 않습니다.</p>'}${(result.error_code||result.ai?.error_code)?`<p class="muted">생성 상태: ${esc(result.error_code||result.ai?.error_code)}</p>`:''}`}
  function chatMarkup(forceAI=false){const c=conversation();return `<label class="check"><input data-org-control="company" type="checkbox" ${state.includeCompany?'checked':''}>같은 조직에서 승인된 전사 KB도 검색</label><p class="muted">기본은 내 부서 KB입니다. 전사 KB는 ${esc(state.org)} 조직 내부에 한하며 다른 조직의 내부 KB를 섞지 않습니다. 조직·부서·검색 범위마다 대화가 분리됩니다.</p><div class="org-conversation">${c.turns.map(turn=>`<article class="org-turn"><h3>질문</h3><p>${esc(turn.question)}</p><p class="muted">${esc(turn.org)} / ${esc(name(turn.department))} · ${turn.includeCompany?'승인된 전사 포함':'내 부서만'} · 적용일 ${esc(turn.asOf)}</p>${responseMarkup(turn.result)}</article>`).join('')||'<p class="empty">이 조직과 검색 범위에서 새 대화를 시작하세요.</p>'}</div><form data-org-form="chat" data-force-ai="${forceAI}"><label>조직 KB에 질문 · UTF-8 2,000바이트 이하<textarea name="question" required maxlength="1000" placeholder="${samplePack==='general'?state.department==='hr'?'휴가 신청에 필요한 내용을 알려주세요.':state.department==='data'?'활성 고객의 집계 기준을 알려주세요.':'입사자 시스템 권한 신청 절차를 알려주세요.':'충전기 문의에 필요한 정보를 알려주세요.'}">${esc(state.chatDraft.question)}</textarea></label><div class="grid"><label>업무 적용일<input type="date" name="as_of" value="${esc(state.asOf)}" required></label><label>정확히 찾을 ID (선택)<input name="exact_id" value="${esc(state.chatDraft.exact)}" placeholder="예: ${samplePack==='general'?({hr:'DEMO-POLICY-001',data:'DEMO-DATA-001',operations:'DEMO-ONBOARD-001'}[state.department]||'문서 ID'):'QA-CH-001'}"></label></div>${forceAI?'<p class="muted">아래 버튼을 누를 때만 검색 근거를 GPT API에 전달해 설명을 요청합니다. 화면 진입이나 범위 선택만으로는 생성하지 않습니다.</p>':`<label class="check"><input type="checkbox" name="generate" ${state.chatDraft.generate?'checked':''} ${aiPaused()?'disabled':''}>검색 근거로 AI 설명도 요청 (선택)</label><p class="muted">기본은 원문 발췌입니다. 선택했을 때만 서버 한도 안에서 AI 설명을 요청합니다.</p>`}${aiPaused()?'<p class="notice">AI 연결 설정 변경 중에는 유료 생성 요청을 사용할 수 없습니다.</p>':''}<button class="primary" ${state.busy||(forceAI&&aiPaused())?'disabled':''}>${state.busy?'처리 중…':forceAI?'AI에 질문하기':'선택한 범위에서 질문하기'}</button></form>`}
  function documentCard(d){return `<article class="org-document"><div class="row"><h3>${esc(d.title||d.name)}</h3><span class="badge">${esc(stateName(d.state))} · v${esc(d.version)}</span></div><p>${esc(name(d.department))} · ${esc(stateName(d.company_status))}</p><p class="muted">적용 ${esc(d.valid_from||'미등록')} ~ ${esc(d.valid_to||'미등록')} · 출처 ${esc(sourceLabel(d.source))}</p><button data-org-action="document" data-doc-id="${esc(d.id)}" ${state.busy?'disabled':''}>문서 본문과 버전 이력 보기</button><details><summary>본문과 공유 상태</summary><pre class="source">${esc(d.content||'본문을 조회한 뒤 검토하세요.')}</pre>${provenance(d.source)}<p>공유 범위: ${esc(d.visibility||'미제공')} · 전사 상태: ${esc(stateName(d.company_status))}</p></details>${state.scope==='department'?`<div class="actions"><button data-org-action="review" data-doc-id="${esc(d.id)}" ${state.busy||!d.content?'disabled':''}>가상 담당자로 확인</button><button data-org-action="request-promotion" data-doc-id="${esc(d.id)}" ${state.busy||d.state!=='confirmed'?'disabled':''}>전사 공유 승인 요청</button><button data-org-action="promote" data-doc-id="${esc(d.id)}" ${state.busy||d.state!=='confirmed'||!['pending','requested'].includes(d.company_status)?'disabled':''}>승인하여 조직 전체에 공유</button><button data-org-action="edit" data-doc-id="${esc(d.id)}" ${state.busy||!d.content?'disabled':''}>새 초안으로 정정</button></div>`:''}</article>`}
  function libraryMarkup(){const sourceDrafts=availableDrafts();const read=`<div class="category-tabs"><button data-org-scope="department" aria-pressed="${state.scope==='department'}">부서 지식</button><button data-org-scope="company" aria-pressed="${state.scope==='company'}">승인된 전사 지식</button><button data-org-action="refresh" ${state.busy?'disabled':''}>목록 새로고침</button></div><p class="muted">초안 등록 → 가상 담당자 확인 → 공유 승인 순서입니다. 정정한 새 버전은 다시 확인·승인해야 합니다. 전사 공유는 선택한 조직 안에서만 이루어집니다.</p>${state.documents.map(documentCard).join('')||'<p class="empty">목록을 새로고침하여 현재 범위의 문서를 확인하세요.</p>'}${state.selected?documentDetails(state.selected):''}${state.editor?editForm(state.editor):''}`;const write=`<form data-org-form="save" class="org-save"><h3>조직 KB에 미확인 초안 등록</h3><button type="button" data-org-action="source-refresh">원문 초안 선택 목록 새로고침</button><label>원문 패널의 초안 선택 (선택)<select data-source-draft><option value="">직접 작성</option>${sourceDrafts.map(d=>`<option value="${esc(d.id)}">${esc(d.title)} · 원문 연결 초안 v${esc(d.version)}</option>`).join('')}</select></label><label>제목<input name="title" required maxlength="200"></label><label>초안 본문 · UTF-8 7,000바이트 이하<textarea name="content" required maxlength="20000" rows="7"></textarea></label><label>출처 설명<input name="source_label" required maxlength="1000" placeholder="예: 가상 담당자 회신 또는 선택한 원문 메모"></label><div class="grid"><label>적용 시작<input name="valid_from" type="date" value="2026-09-01" required></label><label>적용 종료<input name="valid_to" type="date" value="2026-12-31" required></label></div><label>초기 공유 범위<select name="visibility"><option value="department">내 부서</option><option value="private">나만 보기</option></select></label><p class="notice">아래 등록 버튼을 누르면 선택한 초안 본문과 출처 정보가 공개 샘플 서버의 이 체험 세션으로 전송됩니다. 원문 패널에서 파일을 읽기만 하면 전송되지 않습니다. 같은 범용 원문이 서버에 있으면 기존 문서의 새 초안 버전으로 등록하며, 다시 확인해야 검색됩니다.</p><button class="primary" ${state.busy?'disabled':''}>샘플 서버에 초안 등록</button></form>`;const ask=`<section class="org-ai-query"><h3>AI로 지식 조회 (GPT API)</h3><p>현재 조직·부서의 문서에 질문하세요. 전사 KB는 승인된 자료를 포함하도록 직접 선택한 경우에만 검색합니다.</p>${chatMarkup(true)}</section>`;return `<div class="category-tabs" aria-label="공유 지식에서 할 일"><button data-org-purpose="read" aria-pressed="${state.purpose==='read'}">지식 읽기</button><button data-org-purpose="ask" aria-pressed="${state.purpose==='ask'}">질문하기</button><button data-org-purpose="write" aria-pressed="${state.purpose==='write'}">지식 남기기</button></div>${state.purpose==='write'?write:state.purpose==='ask'?ask:read}`}
  function documentDetails(d){return `<section class="org-turn"><button data-org-action="close-document">문서 상세 닫기</button><h3>${esc(d.title||d.name||'문서 본문')}</h3><p class="muted">${esc(name(d.department||state.department))} · v${esc(d.version)} · ${esc(stateName(d.state))}</p><pre class="source">${esc(d.content||'본문 미제공')}</pre>${provenance(d.source)}<details><summary>문서 버전 이력</summary>${(d.history||[]).map(v=>`<article class="evidence"><strong>v${esc(v.version)} · ${esc(stateName(v.state))}</strong><p>${esc(v.reason||'변경 이유 미제공')}</p><pre class="source">${esc(v.content||'본문 미제공')}</pre></article>`).join('')||'<p>제공된 이전 버전이 없습니다.</p>'}</details></section>`}
  function editForm(d){return `<form data-org-form="revise" class="org-save"><h3>${esc(d.title)} · v${esc(d.version)}를 정정</h3><label>새 본문 · UTF-8 7,000바이트 이하<textarea name="content" rows="7" required maxlength="20000">${esc(d.content)}</textarea></label><label>정정 이유<input name="reason" required maxlength="1000"></label><p class="muted">새 버전은 초안이며, 이전 전사 공유 승인을 그대로 이어받지 않습니다.</p><button class="primary" ${state.busy?'disabled':''}>새 초안 버전 저장</button></form>`}
  function render(){if(!container)return;container.innerHTML=`<section class="card org-kb"><div class="eyebrow">SHARED KNOWLEDGE</div><h2>${view==='chat'?'내 조직의 지식으로 질문하기':'함께 쓰는 부서·전사 지식'}</h2><p class="notice">공개 데모의 가상 조직·역할 체험입니다. 조직 선택은 실제 로그인이나 권한 인증이 아닙니다. 보호된 실제 조직 자료와 연결하지 않습니다.</p>${!state.session?`<p>공유 지식을 열면 부서의 문서를 읽고, 질문하거나 새 지식을 남길 수 있습니다.</p><details><summary>연결 정보</summary><span class="badge">API 아직 연결하지 않음</span></details><div class="actions"><button data-org-action="connect" class="primary" ${state.busy||state.connecting?'disabled':''}>${state.connecting?'연결 중…':'공유 지식 열기'}</button></div>`:`<span class="badge good">공유 지식 연결됨</span>${controls()}<details><summary>연결 기술 정보</summary>${vectorMarkup()}</details>${view==='chat'?chatMarkup():libraryMarkup()}`}<p role="status">${esc(state.notice)}</p>${state.notice.includes('미확인 초안')?'<button data-org-purpose="read" class="primary">등록한 초안 확인하기 →</button>':''}${state.error?`<p role="alert" class="scope-reason">${esc(state.error)}</p>`:''}</section>`;bind()}
  async function submitChat(values){if(values.as_of!==state.asOf)changeScope({asOf:values.as_of});if(values.generate&&aiPaused())throw Error('AI 연결 설정 변경 중에는 생성 요청할 수 없습니다.');const ctx={org:state.org,department:state.department,includeCompany:state.includeCompany,asOf:values.as_of,question:values.question};const c=conversation();const result=await request('chat',{question:values.question,include_company:state.includeCompany,as_of:values.as_of,...values.exact_id?{exact_id:values.exact_id}:{},...c.id?{conversation_id:c.id}:{},generate:!!values.generate});c.id=result.conversation_id||c.id;c.turns.push({...ctx,result});state.chatDraft={question:'',exact:'',generate:false};state.vector=result.vector||state.vector}
  function bind(){const chatForm=container.querySelector('[data-org-form=chat]');if(chatForm){chatForm.querySelector('[name=question]').oninput=e=>{state.chatDraft.question=e.target.value};chatForm.querySelector('[name=exact_id]').oninput=e=>{state.chatDraft.exact=e.target.value};const generate=chatForm.querySelector('[name=generate]');if(generate)generate.onchange=e=>{state.chatDraft.generate=e.target.checked}}container.querySelectorAll('[data-org-purpose]').forEach(button=>button.onclick=()=>{state.purpose=button.dataset.orgPurpose;render()});const dateInput=container.querySelector('[data-org-form=chat] [name=as_of]');if(dateInput)dateInput.onchange=()=>changeScope({asOf:dateInput.value});container.querySelectorAll('[data-org-control]').forEach(input=>input.onchange=()=>{const key=input.dataset.orgControl;changeScope(key==='company'?{includeCompany:input.checked}:{[key]:input.value,includeCompany:false,scope:'department'});});container.querySelectorAll('[data-org-scope]').forEach(button=>button.onclick=()=>{changeScope({scope:button.dataset.orgScope});perform(catalog)});container.querySelectorAll('[data-org-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.orgAction,d=currentDocument(button.dataset.docId);if(action==='close-document'){state.selected=null;render();return}if(action==='document')return perform(async()=>{state.selected=await request('document',{id:d.id})});if(action==='source-refresh'){render();return}if(action==='connect')return perform(connect);if(action==='refresh')return perform(catalog);if(action==='edit'){state.editor=d;render();return}perform(async()=>{if(action==='review')await request('review',{id:d.id,version:d.version,state:'confirmed',reason:'가상 담당자가 공개 체험 문서를 확인'});if(action==='request-promotion')await request('request-promotion',{id:d.id,version:d.version});if(action==='promote')await request('promote',{id:d.id,version:d.version,reason:'가상 담당자가 동일 조직 전사 공유 승인'});await catalog();state.notice=action==='promote'?'샘플 서버의 승인 결과를 반영했습니다.':action==='request-promotion'?'공유 승인 요청을 서버에 남겼습니다. 아직 전사 공유된 것은 아닙니다.':'샘플 서버의 확인 결과를 반영했습니다.'})});
   const sourceSelect=container.querySelector('[data-source-draft]');if(sourceSelect)sourceSelect.onchange=()=>{const draft=availableDrafts().find(d=>d.id===sourceSelect.value),form=sourceSelect.form;if(draft){form.title.value=draft.title;form.content.value=draft.content;form.source_label.value=sourceLabel(draft.source);if(draft.validFrom)form.valid_from.value=draft.validFrom;if(draft.validTo)form.valid_to.value=draft.validTo}};if(sourceSelect&&pendingDraft){sourceSelect.value=pendingDraft.id;sourceSelect.onchange()}
   container.querySelectorAll('[data-org-form]').forEach(form=>form.onsubmit=event=>{event.preventDefault();perform(async()=>{const action=form.dataset.orgForm;if(action==='chat'){await submitChat({question:form.question.value.trim(),as_of:form.as_of.value,exact_id:form.exact_id.value.trim(),generate:form.dataset.forceAi==='true'||!!form.generate?.checked});return}if(action==='save'){const draft=availableDrafts().find(d=>d.id===form.querySelector('[data-source-draft]').value);if(form.valid_from.value>form.valid_to.value)throw Error('적용 기간을 확인하세요.');const payload={title:form.title.value,content:form.content.value,valid_from:form.valid_from.value,valid_to:form.valid_to.value,source:{...(draft?.source||{}),label:form.source_label.value},visibility:form.visibility.value};let existing=null;if(draft?.source?.fixture_id){const listing=await request('catalog',{scope:'department'});existing=(listing.documents||[]).find(x=>x.source?.fixture_id===draft.source.fixture_id)}if(existing)await request('revise',{...payload,id:existing.id,version:existing.version,reason:'선택한 브라우저 최신 문서를 새 초안으로 반영'});else await request('save',{...payload,identifiers:[]});pendingDraft=null;state.notice='서버에 미확인 초안으로 등록했습니다. 확인과 전사 승인은 별도입니다.'}if(action==='revise'){await request('revise',{id:state.editor.id,version:state.editor.version,content:form.content.value,reason:form.reason.value});state.editor=null;state.notice='정정된 새 초안을 저장했습니다. 전사 공유는 재승인이 필요합니다.'}await catalog()})});
  }
  return {prepareDraft(draft){changeScope({department:draft.department,includeCompany:false,scope:'department'});pendingDraft=draft;state.purpose='write';state.notice='선택한 브라우저 KB의 최신 본문을 등록 양식에 준비했습니다. 연결 후 등록하고 담당자 확인을 거쳐 질문하세요.';render();const target=container?.querySelector('[data-org-form=save]')||container;target?.scrollIntoView({block:'start'})},focusAI(){state.purpose='ask';render();if(!container)return;const section=container.querySelector('.org-ai-query')||container;section.scrollIntoView({block:'start'});section.querySelector('[name=question], [data-org-action=connect]')?.focus({preventScroll:true})},mount(target,{mode='chat'}={}){container=target;view=mode;render();return ()=>{if(container===target){epoch++;container=null}}},changeScope,connect,catalog,submitChat,request,getState:()=>state};
 }
 root.KnowHowOrganizationUI={createController};
})(window);
